import { UFV_SYSTEM_PROJECT_JOURNEY_WORKFLOW_STAGES_LEGACY_CONFIG } from "@/lib/project-journeys";
import type { TProject, TProjectComissionedUser } from "@/utils/schemas/projects";

export function createEmptyDirectProject(): TProject {
	const now = new Date().toISOString();

	return {
		qtde: 0,
		nomeDoContrato: "",
		nomeDoProjeto: "",
		cpf_cnpj: "",
		telefone: "",
		email: "",
		dataNascimento: null,
		cep: "",
		uf: "",
		cidade: "",
		bairro: "",
		logradouro: "",
		numeroResidencia: "",
		longitude: "",
		latitude: "",
		regional: "NAO DEFINIDO",
		tipoDeServico: "SISTEMA FOTOVOLTAICO",
		codigoSVB: "",
		segmento: "RESIDENCIAL",
		canalVenda: "NAO DEFINIDO",
		obsComercial: "",
		linkDrive: "",
		inscricaoRural: "",
		idClienteCRM: null,
		idProjetoCRM: null,
		idMarketing: null,
		idPropostaCRM: null,
		idSolicitacaoContrato: null,
		idVisitaTecnica: null,
		idParceiro: null,
		nomeParceiro: null,
		insider: "NAO DEFINIDO",
		vendedor: {
			idCRM: null,
			codigo: null,
			nome: "NAO DEFINIDO",
			avatar: null,
		},
		visitaTecnica: {
			status: null,
			tecnico: null,
			saidaDoCliente: null,
			amperagem: "",
			tipoDaTelha: null,
		},
		padrao: {
			tipo: "NAO DEFINIDO",
			tipoEntrada: undefined,
			caixaConjugada: "NAO",
			respPagamento: null,
			respInstalacao: null,
			valor: 0,
			aumentoCarga: {
				aplicavel: false,
				dataEfetivacao: null,
			},
		},
		estruturaPersonalizada: {
			aplicavel: "NAO",
			tipo: "N/A",
			respPagamento: null,
			valor: 0,
			status: "N/A",
			statusEntrega: "NAO DEFINIDO",
			dataEntrega: null,
		},
		contrato: {
			status: "SOLICITADO",
			dataSolicitacao: now,
			dataLiberacao: null,
			dataAssinatura: null,
			formaAssinatura: "NAO DEFINIDO" as TProject["contrato"]["formaAssinatura"],
		},
		pagamento: {
			status: "NAO DEFINIDO",
			forma: null,
			credor: null,
			credorNomeGerente: "",
			credorContatoGerente: "",
			pagador: {
				nome: "",
				cpfCnpj: "",
				telefone: "",
				email: "",
				localizacao: {
					cep: "",
					uf: "",
					cidade: "",
					bairro: "",
					endereco: "",
					numeroOuIdentificador: "",
					complemento: "",
				},
			},
			contatoPagador: "",
			cpf_cnpjPagador: "",
			negociacao: "",
			metodo: "NAO DEFINIDO",
			retorno: 0,
			cobrancaFeita: false,
			dataRecebimento: null,
		},
		faturamento: {
			necessarioNotaFiscalAdiantada: false,
			necessarioCodigoFiname: false,
			necessarioInscricaoRural: false,
			previsaoFaturamento: "",
			cnpjFaturamento: "",
			empresaFaturamento: null,
			concluido: false,
			observacoes: "",
		},
		compra: {
			localizacaoEntrega: {
				cep: "",
				uf: "",
				cidade: "",
				bairro: "",
				endereco: "",
				numeroOuIdentificador: "",
				complemento: "",
				latitude: "",
				longitude: "",
			},
			status: "NAO DEFINIDO",
			statusLiberacao: "NAO DEFINIDO",
			tipoDoKit: "NAO DEFINIDO",
			valorDoKit: 0,
			previsaoValorDoKit: 0,
			kitInfo: "",
			fornecedor: "NAO DEFINIDO",
			localEntrega: "MESMO DO PROJETO",
			informacoes: "",
			rastreio: "",
			statusEntrega: "NAO DEFINIDO",
		},
		dadosCemig: {
			titularProjeto: "",
			numeroInstalacao: "",
			distCreditos: "NAO DEFINIDO" as TProject["dadosCemig"]["distCreditos"],
			qtdeDistCreditos: 0,
		},
		sistema: {
			qtdeModulos: 0,
			potModulos: "",
			potPico: 0,
			topologia: null,
			inversor: "",
			tipoControlador: "",
			marcaControlador: "",
			qtdeControlador: null,
			correnteControlador: null,
			tipoBateria: "",
			marcaBateria: "",
			qtdeBateria: null,
			capacidadeBateria: null,
			marcaBomba: "",
			qtdeBomba: null,
			potBomba: null,
			valorProjeto: 0,
		},
		seguro: {
			aplicavel: false,
			valor: 0,
			duracao: null,
			dataInicio: null,
			dataFim: null,
		},
		projeto: {
			iniciar: "NAO DEFINIDO",
			projetista: {
				nome: "NAO DEFINIDO",
				codigo: "",
			},
			dataLiberacaoDocumentacao: null,
			dataAssDocumentacao: null,
			diagramaUnifilar: null,
			desenhoTelhado: null,
			mapaDeMicro: null,
			aumentoDeCarga: "NAO",
			acStatus: "NAO DEFINIDO",
			projetoConcluido: "NAO",
			realizarHomologacao: true,
		},
		homologacao: {
			homologar: true,
			status: "PENDENTE",
			potencia: null,
			distribuidora: "CEMIG D",
			observacoes: "",
			pendencias: {
				desenhos: null,
				diagramas: null,
				formularios: null,
				mapasDeMicro: null,
				distribuicoes: null,
			},
			oportunidade: {
				id: "",
				nome: "",
			},
			titular: {
				nome: "",
				contato: "",
				identificador: "",
			},
			fastTrack: false,
			equipamentos: [],
			localizacao: {
				uf: "",
				cidade: "",
			},
			instalacao: {
				grupo: "RESIDENCIAL",
				numeroCliente: "",
				numeroInstalacao: "",
				dependentes: [],
			},
			documentacao: {
				formaAssinatura: "DIGITAL",
				dataInicioElaboracao: null,
				dataConclusaoElaboracao: null,
				dataLiberacao: null,
				dataAssinatura: null,
			},
			acesso: {
				codigo: "",
				dataSolicitacao: null,
				dataResposta: null,
			},
			atualizacoes: [],
			vistoria: {
				dataSolicitacao: null,
				dataEfetivacao: null,
			},
			dataEfetivacao: null,
			dataLiberacao: null,
		},
		parecer: {
			statusDoParecerDeAcesso: "NAO DEFINIDO",
			dataParecerDeAcesso: null,
			parecerReprovado: "NAO",
			qtdeReprovas: 0,
			motivoReprova: null,
		},
		vistoria: {
			dataPedido: null,
			status: "NAO DEFINIDO",
			vistoriaReprovada: "NAO",
			qtdeReprovas: 0,
			motivoReprova: null,
		},
		medidor: {
			data: null,
			status: "NAO DEFINIDO",
		},
		oem: {
			aplicavel: false,
			duracao: 0,
			qtdeManutencoes: 0,
			diagnostico: null,
			dataInicio: null,
			dataFim: null,
			plano: null,
			qtdeModulos: null,
			qtdeInversores: null,
			valor: 0,
		},
		obra: ({
			laudo: "NAO DEFINIDO",
			observacoes: "",
			statusSolicitacao: "NAO SOLICITADA",
			entrada: null,
			saida: null,
			statusDaObra: "NAO DEFINIDO",
			equipeResp: "NAO DEFINIDO",
			checklist: undefined,
			trafo: "NAO",
		} as unknown) as TProject["obra"],
		material: ({
			statusSeparacao: "NAO DEFINIDO",
			previsaoCustos: 0,
			efetivoCustos: 0,
			materialFaltante: "",
		} as unknown) as TProject["material"],
		manutencaoPreventiva: { status: "NAO REALIZADO", data: null },
		manutencoes: [],
		relatorios: {
			envioUm: { status: "NAO REALIZADO", data: null },
			envioDois: { status: "NAO REALIZADO", data: null },
			envioTres: { status: "NAO REALIZADO", data: null },
			envioQuatro: { status: "NAO REALIZADO", data: null },
		},
		conferencias: {
			usinaLigada: { status: "NAO REALIZADO", data: null },
			monitoramentoFeito: { status: "NAO REALIZADO", data: null },
			energiaInjetada: { status: "NAO REALIZADO", data: null },
		},
		app: {
			data: null,
			login: "",
			senha: "",
		},
		produtos: [],
		servicos: [],
		indicacao: {
			quemIndicou: null,
			contato: null,
		},
		ondeTrabalha: "",
		jornada: {
			anotacoes: "",
			estagios: UFV_SYSTEM_PROJECT_JOURNEY_WORKFLOW_STAGES_LEGACY_CONFIG,
		} as TProject["jornada"],
		possuiDeficiencia: "NAO",
		qualDeficiencia: "",
		nps: undefined,
		links: {
			documentos: [],
			visitaTecnica: [],
			chamadosSuporte: [],
			chamadosSuprimentos: [],
			contratos: [],
			equipamentos: [],
			manutencaoPreventiva: [],
			obras: [],
			projetos: [],
		},
		comissoes: {
			comissionados: [] as TProjectComissionedUser[],
			valorComissionavel: 0,
			itensComissionaveis: ["SISTEMA", "PADRÃO", "ESTRUTURA PERSONALIZADA", "OEM", "SEGURO"] as NonNullable<TProject["comissoes"]>["itensComissionaveis"],
		},
		alocacoes: [],
		satisfacao: {},
	} as unknown as TProject;
}
