import { MdEast, MdNorth, MdNorthEast, MdNorthWest, MdSouth, MdSouthEast, MdSouthWest, MdWest } from 'react-icons/md'

export const supplementationStatus = [
  {
    id: 1,
    label: 'NÃO DEFINIDO',
    value: 'NÃO DEFINIDO',
  },
  {
    id: 2,
    label: 'CONCLUIDA',
    value: 'CONCLUIDA',
  },
  {
    id: 3,
    label: 'COMPRA REALIZADA',
    value: 'COMPRA REALIZADA',
  },
  {
    id: 4,
    label: 'AGUARDANDO PARECER DE ACESSO',
    value: 'AGUARDANDO PARECER DE ACESSO',
  },
  {
    id: 5,
    label: 'AGUARDANDO PAGAMENTO',
    value: 'AGUARDANDO PAGAMENTO',
  },
  {
    id: 6,
    label: 'PREDEFINIÇÃO DE EQUIPAMENTOS',
    value: 'PREDEFINIÇÃO DE EQUIPAMENTOS',
  },
]
export const contractStatus = [
  {
    id: 1,
    value: 'AGUARDANDO SOLICITAÇÃO',
    label: 'AGUARDANDO SOLICITAÇÃO',
  },
  {
    id: 2,
    value: 'SOLICITADO',
    label: 'SOLICITADO',
  },
  {
    id: 3,
    value: 'NÃO ASSINADO',
    label: 'NÃO ASSINADO',
  },
  {
    id: 4,
    value: 'ASSINADO',
    label: 'ASSINADO',
  },
  { id: 5, value: 'RESCISÃO DE CONTRATO', label: 'RESCISÃO DE CONTRATO' },
]
export const serviceTypes = [
  {
    id: 1,
    label: 'SISTEMA FOTOVOLTAICO',
    value: 'SISTEMA FOTOVOLTAICO',
  },
  {
    id: 2,
    label: 'SISTEMA FOTOVOLTAICO (OFF GRID)',
    value: 'SISTEMA FOTOVOLTAICO (OFF GRID)',
  },
  {
    id: 3,
    label: 'AUMENTO DE SISTEMA FOTOVOLTAICO',
    value: 'AUMENTO DE SISTEMA FOTOVOLTAICO',
  },
  {
    id: 4,
    label: 'BOMBA SOLAR',
    value: 'BOMBA SOLAR',
  },
  {
    id: 5,
    label: 'OPERAÇÃO E MANUTENÇÃO',
    value: 'OPERAÇÃO E MANUTENÇÃO',
  },
  {
    id: 6,
    label: 'TROCA DE PADRÃO',
    value: 'TROCA DE PADRÃO',
  },
  {
    id: 7,
    label: 'REFORMA DE PADRÃO',
    value: 'REFORMA DE PADRÃO',
  },
  {
    id: 8,
    label: 'MANUTENÇÃO CORRETIVA',
    value: 'MANUTENÇÃO CORRETIVA',
  },
  {
    id: 9,
    label: 'MANUTENÇÃO PREVENTIVA',
    value: 'MANUTENÇÃO PREVENTIVA',
  },
  {
    id: 10,
    label: 'MONTAGEM E DESMONTAGEM',
    value: 'MONTAGEM E DESMONTAGEM',
  },
  {
    id: 11,
    label: 'TROCA DE STRING BOX',
    value: 'TROCA DE STRING BOX',
  },
  {
    id: 12,
    label: 'SUBESTAÇÃO DE ENERGIA',
    value: 'SUBESTAÇÃO DE ENERGIA',
  },
]
export const allSellers = [
  {
    id: 1,
    active: true,
    label: 'ARTHUR CARVALHO',
    value: 'ARTHUR CARVALHO',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 2,
    active: true,
    label: 'ARTUR MILANE',
    value: 'ARTUR MILANE',
    qualification: 'PLENO',
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 3,
    active: false,
    label: 'CARLOS MARQUES',
    value: 'CARLOS MARQUES',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 4,
    active: true,
    label: 'DEVISSON LIMA',
    value: 'DEVISSON LIMA',
    qualification: 'JUNIOR',
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 5,
    active: true,
    label: 'DIOMAR HONORIO',
    value: 'DIOMAR HONORIO',
    qualification: 'PLENO',
    comissionAsActive: 5,
    comissionWithInside: 4,
  },
  {
    id: 6,
    active: false,
    label: 'GETULIO EDUARDO',
    value: 'GETULIO EDUARDO',
    qualification: 'PLENO',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 7,
    active: true,
    label: 'GLAIDSTONE JOSÉ',
    value: 'GLAIDSTONE JOSÉ',
    qualification: 'JUNIOR',
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 8,
    active: false,
    label: 'JESSICA PARANAIBA',
    value: 'JESSICA PARANAIBA',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 9,
    active: false,
    label: 'JORGINHO HABIB',
    value: 'JORGINHO HABIB',
    qualification: 'JUNIOR',
    comissionAsActive: 3,
    comissionWithInside: 2,
  },
  {
    id: 10,
    active: true,
    label: 'JULIANO SILVA',
    value: 'JULIANO SILVA',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 11,
    active: true,
    label: 'MATHEUS OLIVEIRA',
    value: 'MATHEUS OLIVEIRA',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 12,
    active: true,
    label: 'NEIDSON FILHO',
    value: 'NEIDSON FILHO',
    qualification: 'JUNIOR',
    comissionAsActive: 5,
    comissionWithInside: 4,
  },
  {
    id: 13,
    active: true,
    label: 'RAFAEL FEO',
    value: 'RAFAEL FEO',
    qualification: 'PLENO',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 14,
    active: false,
    label: 'ROMES ALVES',
    value: 'ROMES ALVES',
    qualification: 'PLENO',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 15,
    active: true,
    label: 'RODRIGO MORAIS',
    value: 'RODRIGO MORAIS',
    qualification: 'PLENO',
    comissionAsActive: 4,
    comissionWithInside: 3,
  },
  {
    id: 16,
    active: false,
    label: 'LUCIANO MUNIZ',
    value: 'LUCIANO MUNIZ',
    qualification: 'PLENO',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 17,
    active: true,
    label: 'DIONISIO JUNIOR',
    value: 'DIONISIO JUNIOR',
    qualification: 'PLENO',
    comissionAsActive: 5,
    comissionWithInside: 4,
  },
  {
    id: 18,
    active: true,
    label: 'LEANDRO VIALI',
    value: 'LEANDRO VIALI',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
  {
    id: 19,
    active: false,
    label: 'GUILHERME LIMA',
    value: 'GUILHERME LIMA',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 20,
    active: false,
    label: 'LUCIANO JORGE',
    value: 'LUCIANO JORGE',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 21,
    active: true,
    label: 'STENIO DE ASSIS',
    value: 'STENIO DE ASSIS',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 22,
    active: true,
    label: 'RONIVALDO MARTINS',
    value: 'RONIVALDO MARTINS',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 23,
    active: true,
    label: 'DIOGO PAULINO',
    value: 'DIOGO PAULINO',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 24,
    active: true,
    label: 'ADRIANO ARANTES',
    value: 'ADRIANO ARANTES',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 25,
    active: false,
    label: 'ARIÁDNNY APARECIDA',
    value: 'ARIÁDNNY APARECIDA',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 26,
    active: false,
    label: 'DÁFINY VILLANO',
    value: 'DÁFINY VILLANO',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.9,
    comissionWithInside: 0.9,
  },
  {
    id: 27,
    active: false,
    label: 'ARTHUR ALEXANDER',
    value: 'ARTHUR ALEXANDER',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 28,
    active: false,
    label: 'FELIPE RIBEIRO',
    value: 'FELIPE RIBEIRO',
    qualification: 'INSIDE SENIOR',
    comissionAsActive: 0.25,
    comissionWithInside: 0.25,
  },
  {
    id: 29,
    active: false,
    label: 'ADAILSON COSTA',
    value: 'ADAILSON COSTA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 30,
    active: true,
    label: 'LUCIANO LOPES',
    value: 'LUCIANO LOPES',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 31,
    active: true,
    label: 'RODRIGO DE MORAIS',
    value: 'RODRIGO DE MORAIS',
    qualification: 'PLENO',
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 32,
    active: true,
    label: 'EURIPEDES JUNIOR',
    value: 'EURIPEDES JUNIOR',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 33,
    active: false,
    label: 'FRANCO MUSTAFE',
    value: 'FRANCO MUSTAFE',
    qualification: undefined,
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 34,
    active: false,
    label: 'ALLISSON OSCAR',
    value: 'ALLISSON OSCAR',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 35,
    active: undefined,
    label: 'WILLIAM MENEZES',
    value: 'WILLIAM MENEZES',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 36,
    active: false,
    label: 'MARIANA DE SOUZA',
    value: 'MARIANA DE SOUZA',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.9,
    comissionWithInside: 0.9,
  },
  {
    id: 37,
    active: false,
    label: 'CÉLIO JUNIOR',
    value: 'CÉLIO JUNIOR',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 38,
    active: true,
    label: 'THIAGO DE PAULA',
    value: 'THIAGO DE PAULA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 39,
    active: false,
    label: 'GLEITON RESENDE',
    value: 'GLEITON RESENDE',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 40,
    active: false,
    label: 'ANA PAULA PEREIRA',
    value: 'ANA PAULA PEREIRA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 41,
    active: false,
    label: 'GRASIELE DA SILVA',
    value: 'GRASIELE DA SILVA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 42,
    active: true,
    label: 'MARCUS VINÍCIUS',
    value: 'MARCUS VINÍCIUS',
    qualification: undefined,
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 43,
    active: true,
    label: 'LEONARDO VILARINHO',
    value: 'LEONARDO VILARINHO',
    qualification: undefined,
    comissionAsActive: 1.5,
    comissionWithInside: 1,
  },
  {
    id: 44,
    active: true,
    label: 'ROBERTH JUNQUEIRA',
    value: 'ROBERTH JUNQUEIRA',
    qualification: undefined,
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 45,
    active: true,
    label: 'GABRIEL MARTINS',
    value: 'GABRIEL MARTINS',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 46,
    active: true,
    label: 'LUCAS FERNANDES',
    value: 'LUCAS FERNANDES',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 47,
    active: true,
    label: 'GABRIEL EMANUEL',
    value: 'GABRIEL EMANUEL',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
  {
    id: 48,
    active: true,
    label: 'YASMIM ARAUJO',
    value: 'YASMIM ARAUJO',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
  {
    id: 49,
    active: true,
    label: 'RAILDO CARVALHO',
    value: 'RAILDO CARVALHO',
    qualification: undefined,
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 50,
    active: true,
    label: 'SEBASTIÃO NETO',
    value: 'SEBASTIÃO NETO',
    qualification: undefined,
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 51,
    active: true,
    label: 'AMANDA SANTOS',
    value: 'AMANDA SANTOS',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
]
export const insiders = allSellers.filter((s) => s.qualification?.includes('INSIDE'))
export const technicalAnalysisStatus = [
  { id: 1, label: 'CONCLUIDO', value: 'CONCLUIDO' },
  { id: 2, label: 'EM ANÁLISE TÉCNICA', value: 'EM ANÁLISE TÉCNICA' },
  {
    id: 3,
    label: 'PENDÊNCIA COMERCIAL',
    value: 'PENDÊNCIA COMERCIAL',
  },
  { id: 4, label: 'VISITA IN LOCO', value: 'VISITA IN LOCO' },
  { id: 5, label: 'REJEITADA', value: 'REJEITADA' },
  { id: 6, label: 'PENDENTE', value: 'PENDENTE' },
]
export const technicalAnalysisSolicitationTypes = [
  {
    id: 1,
    label: 'VISITA TÉCNICA REMOTA - URBANA',
    value: 'VISITA TÉCNICA REMOTA - URBANA',
  },
  {
    id: 2,
    label: 'VISITA TÉCNICA REMOTA - RURAL',
    value: 'VISITA TÉCNICA REMOTA - RURAL',
  },
  {
    id: 3,
    label: 'VISITA TÉCNICA IN LOCO - URBANA',
    value: 'VISITA TÉCNICA IN LOCO - URBANA',
  },
  {
    id: 4,
    label: 'VISITA TÉCNICA IN LOCO - RURAL',
    value: 'VISITA TÉCNICA IN LOCO - RURAL',
  },
  {
    id: 5,
    label: 'AUMENTO DE SISTEMA',
    value: 'AUMENTO DE SISTEMA',
  },
  { id: 6, label: 'DESENHO PERSONALIZADO', value: 'DESENHO PERSONALIZADO' },
  { id: 7, label: 'ORÇAMENTAÇÃO', value: 'ORÇAMENTAÇÃO' },
]
export const technicalAnalysisPendencyCategories = [
  { id: 1, label: 'PENDÊNCIA COMERCIAL', value: 'PENDÊNCIA COMERCIAL' },
  { id: 2, label: 'PENDÊNCIA COM TERCEIROS', value: 'PENDÊNCIA COM TERCEIROS' }, // COTAÇÕES, ETC
  { id: 3, label: 'PENDÊNCIA CONCESSIONÁRIA', value: 'PENDÊNCIA CONCESSIONÁRIA' },
  { id: 4, label: 'OUTROS', value: 'OUTROS' },
]
export const engineeringAnalysts = [
  {
    id: 1,
    nome: 'Andrew Borges Alexander',
    apelido: 'ANDREW',
    avatar_url:
      'https://firebasestorage.googleapis.com/v0/b/sistemaampere.appspot.com/o/usuarios%2Favatar-andrew_borges_alexander?alt=media&token=1d9787c0-7fd9-4343-9674-1ee69c03709b',
  },
  {
    id: 2,
    nome: 'Tulio Medeiros',
    apelido: 'TULIO',
    avatar_url:
      'https://firebasestorage.googleapis.com/v0/b/sistemaampere.appspot.com/o/usuarios%2Favatar-tulio_medeiros?alt=media&token=233e20b5-520d-473a-9e7e-f603a0b9493c',
  },
]
export const accessGrantingStatus = [
  {
    id: 1,
    label: 'AGUARDANDO ASSINATURA',
    value: 'AGUARDANDO ASSINATURA',
  },
  {
    id: 2,
    label: 'AGUARDANDO AUMENTO DE CARGA',
    value: 'AGUARDANDO AUMENTO DE CARGA',
  },
  {
    id: 3,
    label: 'SOLICITAR TROCA DE TITULARIDADE',
    value: 'SOLICITAR TROCA DE TITULARIDADE',
  },
  {
    id: 3,
    label: 'AGUARDANDO FATURAMENTO ART',
    value: 'AGUARDANDO FATURAMENTO ART',
  },
  {
    id: 4,
    label: 'AGUARDANDO RESPOSTA DA CONCESSIONARIA',
    value: 'AGUARDANDO RESPOSTA DA CONCESSIONARIA',
  },
  {
    id: 5,
    label: 'AGUARDANDO TROCA DE TITULARIDADE',
    value: 'AGUARDANDO TROCA DE TITULARIDADE',
  },
  {
    id: 6,
    label: 'PARECER DE ACESSO SUSPENSO',
    value: 'PARECER DE ACESSO SUSPENSO',
  },
  {
    id: 7,
    label: 'PARECER DE ACESSO APROVADO',
    value: 'PARECER DE ACESSO APROVADO',
  },
  { id: 8, label: 'PENDENCIAS', value: 'PENDENCIAS' },
  {
    id: 9,
    label: 'PARECER DE ACESSO COM OBRAS',
    value: 'PARECER DE ACESSO COM OBRAS',
  },
  {
    id: 10,
    label: 'AGUARDANDO ANÁLISE DE CARGA',
    value: 'AGUARDANDO ANÁLISE DE CARGA',
  },
  {
    id: 11,
    label: 'AGUARDANDO CORREÇÃO DE EQUIPAMENTO',
    value: 'AGUARDANDO CORREÇÃO DE EQUIPAMENTO',
  },
  {
    id: 12,
    label: 'PARECER APROVADO - NOTURNO',
    value: 'PARECER APROVADO - NOTURNO',
  },
  {
    id: 13,
    label: 'PENDÊNCIAS - DÉBITOS',
    value: 'PENDÊNCIAS - DÉBITOS',
  },
  { id: 14, label: 'NÃO DEFINIDO', value: 'NÃO DEFINIDO' },
]
export const executionStatus = [
  { id: 1, label: 'AGENDADA', value: 'AGENDADA' },
  { id: 2, label: 'AGUARDANDO AGENDAMENTO', value: 'AGUARDANDO AGENDAMENTO' },
  { id: 3, label: 'CONCLUIDA', value: 'CONCLUIDA' },
  { id: 4, label: 'EM ANDAMENTO', value: 'EM ANDAMENTO' },
  { id: 5, label: 'OBRA CANCELADA', value: 'OBRA CANCELADA' },
  { id: 6, label: 'CASA EM CONSTRUÇÃO', value: 'CASA EM CONSTRUÇÃO' },
  { id: 7, label: 'NÃO DEFINIDO', value: 'NÃO DEFINIDO' },
]
export const inspectionStatus = [
  { id: 1, label: 'REALIZADA', value: 'REALIZADA' },
  { id: 2, label: 'AGUARDANDO OBRA DE REDE', value: 'AGUARDANDO OBRA DE REDE' },
  { id: 3, label: 'AGUARDANDO CONCESSIONARIA', value: 'AGUARDANDO CONCESSIONARIA' },
  { id: 4, label: 'NÃO DEFINIDO', value: 'NÃO DEFINIDO' },
]
export const reliabilityAnalysts = [
  { id: 1, value: 'POLLIANA CRISTINA DE REZENDE', label: 'POLLIANA', cod: 1 },
  { id: 2, value: 'ALINE APARECIDA RODRIGUES CARVALHO', label: 'ALINE', cod: 21 },
  { id: 3, value: 'ANDREW BORGES ALEXANDER', label: 'ANDREW', cod: 44 },
  { id: 4, value: 'JORDANA ALVES DE FREITAS', label: 'JORDANA', cod: 29 },
  { id: 5, value: 'ANDRIELLY GARCIA DOS SANTOS MARQUES', label: 'ANDRIELLY', cod: 51 },
  { id: 6, value: 'GLENDA ELIAS NASCIMENTO SANTOS', label: 'GLENDA', cod: 52 },
  { id: 7, value: 'TULIO HENRIQUE SILVA MEDEIROS', label: 'TULIO', cod: 53 },
  { id: 8, value: 'EDUARDO HENRIQUE DOMINGOS DE MORAES', label: 'EDUARDO', cod: 54 },
  { id: 9, value: 'LAZARO MARQUES', label: 'LAZARO', cod: 55 },
  { id: 10, value: 'NÃO DEFINIDO', label: 'NÃO DEFINIDO', cod: 0 },
]
export const additionalCostsCategories = [
  {
    id: 1,
    label: 'INSTALAÇÃO',
    value: 'INSTALAÇÃO',
  },
  {
    id: 2,
    label: 'PADRÃO',
    value: 'PADRÃO',
  },
  {
    id: 3,
    label: 'ESTRUTURA',
    value: 'ESTRUTURA',
  },
  {
    id: 4,
    label: 'OUTROS',
    value: 'OUTROS',
  },
]
export const units = [
  { id: 1, label: 'UNIDADE (UN)', value: 'UN' },
  { id: 2, label: 'PACOTE (PC)', value: 'PC' },
  { id: 3, label: 'QUILO (KG)', value: 'KG' },
  { id: 4, label: 'CX (CAIXA)', value: 'CX' },
  { id: 5, label: 'M (METRO)', value: 'M' },
  { id: 6, label: 'METRO QUADRADO (M²)', value: 'M²' },
  { id: 7, label: 'METRO CÚBICO (M³)', value: 'M³' },
  { id: 8, label: 'LITROS (L)', value: 'L' },
  { id: 9, label: 'MESA', value: 'MESA' },
]
export const inverterFixationOptions = [
  { id: 1, label: 'NÃO DEFINIDO', value: 'NÃO DEFINIDO' },
  { id: 2, label: 'ALVENARIA', value: 'ALVENARIA' },
  { id: 3, label: 'LANCE DE MURO', value: 'LANCE DE MURO' },
  { id: 4, label: 'PILAR', value: 'PILAR' },
  { id: 5, label: 'OUTRO(DESCREVA EM OBSERVAÇÕES)', value: 'OUTRO(DESCREVA EM OBSERVAÇÕES)' },
]
export const roofTiles = [
  { id: 1, label: 'NÃO DEFINIDO', value: 'NÃO DEFINIDO' },
  { id: 2, label: 'PORTUGUESA', value: 'PORTUGUESA' },
  { id: 3, label: 'FRANCESA', value: 'FRANCESA' },
  { id: 4, label: 'ROMANA', value: 'ROMANA' },
  { id: 5, label: 'CIMENTO', value: 'CIMENTO' },
  { id: 6, label: 'ETHERNIT', value: 'ETHERNIT' },
  { id: 7, label: 'SANDUÍCHE', value: 'SANDUÍCHE' },
  { id: 8, label: 'AMERICANA', value: 'AMERICANA' },
  { id: 9, label: 'ZINCO', value: 'ZINCO' },
  { id: 10, label: 'CAPE E BICA', value: 'CAPE E BICA' },
  { id: 11, label: 'LAJE', value: 'LAJE' },
]
export const structureTypes = [
  { id: 1, label: 'INCLINAÇÃO', value: 'INCLINAÇÃO' },
  { id: 2, label: 'SOLO', value: 'SOLO' },
  { id: 3, label: 'TELHADO', value: 'TELHADO' },
  { id: 4, label: 'BARRACÃO', value: 'BARRACÃO' },
  { id: 5, label: 'CARPORT', value: 'CARPORT' },
  { id: 6, label: 'ESTRUTURA PERSONALIZADA', value: 'ESTRUTURA PERSONALIZADA' },
  { id: 7, label: 'N/A', value: 'N/A' },
]
export const supplyOptions = {
  GRAMPO: {
    tipos: ['FINAL', 'INTERMEDIÁRIO'],
    grandeza: 'UNIDADE',
  },
  TRILHO: {
    tipos: ['1,85', '2,20', '2,36', '2,40', '2,50', '3,20', '3,30', '4,20', '4,70', '4,80'],
    grandeza: 'UNIDADE',
  },
  'PARAFUSO FIBROCIMENTO': {
    tipos: ['MADEIRA', 'FERRO'],
    grandeza: 'UNIDADE',
  },
  'PAR DE JUNÇÃO': {
    tipos: ['TRILHO'],
    grandeza: 'UNIDADE',
  },
  CABO: {
    tipos: ['SOLAR(VERMELHO)', 'SOLAR(PRETO)'],
    grandeza: 'METRO',
  },
  'CONECTOR MC4': {
    tipos: ['-'],
    grandeza: 'UNIDADE',
  },
  'ESTRUTURA SOLO': {
    tipos: ['MESA DUPLA'],
    grandeza: 'MESA',
  },
}
export const additionalServicesResponsibilityOptions = [
  { id: 1, label: 'NÃO', value: 'NÃO' },
  { id: 2, label: 'SIM - RESPONSABILIDADE CLIENTE', value: 'SIM - RESPONSABILIDADE CLIENTE' },
  { id: 3, label: 'SIM - RESPONSABILIDADE AMPÈRE', value: 'SIM - RESPONSABILIDADE AMPÈRE' },
]
export const amperageOptions = [
  { id: 1, label: '40A', value: '40A' },
  { id: 2, label: '50A', value: '50A' },
  { id: 3, label: '60A', value: '60A' },
  { id: 4, label: '63A', value: '63A' },
  { id: 5, label: '70A', value: '70A' },
  { id: 6, label: '90A', value: '90A' },
  { id: 7, label: '100A', value: '100A' },
  { id: 8, label: '200A', value: '200A' },
]
export const energyPATypes = [
  { id: 1, label: 'CONTRA À REDE', value: 'CONTRA À REDE' },
  { id: 2, label: 'À FAVOR DA REDE', value: 'À FAVOR DA REDE' },
]
export const energyPAConnectionTypes = [
  { id: 1, label: 'AÉREO', value: 'AÉREO' },
  { id: 2, label: 'SUBTERRÂNEO', value: 'SUBTERRÂNEO' },
]
export const energyMeterBoxModels = [
  { id: 1, label: 'CM-1', value: 'CM-1' },
  { id: 2, label: 'CM-2', value: 'CM-2' },
  { id: 3, label: 'CM-3', value: 'CM-3' },
  { id: 4, label: 'CM-4', value: 'CM-4' },
  { id: 5, label: 'CM-8', value: 'CM-8' },
  { id: 6, label: 'CM-9', value: 'CM-9' },
  { id: 7, label: 'CM-13', value: 'CM-13' },
  { id: 8, label: 'CM-14', value: 'CM-14' },
  { id: 9, label: 'CM-18', value: 'CM-18' },
]
export const technicalAnalysisReportTypes = [
  {
    id: 1,
    label: 'LAUDO TÉCNICO(URBANO)',
    value: 'LAUDO TÉCNICO(URBANO)',
  },
  {
    id: 2,
    label: 'LAUDO SIMPLES(URBANO)',
    value: 'LAUDO SIMPLES(URBANO)',
  },
  {
    id: 3,
    label: 'LAUDO INTERMEDIÁRIO(URBANO)',
    value: 'LAUDO INTERMEDIÁRIO(URBANO)',
  },
  {
    id: 4,
    label: 'LAUDO TÉCNICO(RURAL)',
    value: 'LAUDO TÉCNICO(RURAL)',
  },
  {
    id: 5,
    label: 'LAUDO SIMPLES(RURAL)',
    value: 'LAUDO SIMPLES(RURAL)',
  },
  {
    id: 6,
    label: 'FORMULÁRIO(URBANO)',
    value: 'FORMULÁRIO(URBANO)',
  },
  {
    id: 7,
    label: 'FORMULÁRIO(RURAL)',
    value: 'FORMULÁRIO(RURAL)',
  },
]
export const orientationIcons = {
  LESTE: MdEast,
  NORDESTE: MdNorthEast,
  NORTE: MdNorth,
  NOROESTE: MdNorthWest,
  OESTE: MdWest,
  SUDOESTE: MdSouthWest,
  SUL: MdSouth,
  SUDESTE: MdSouthEast,
}
