export const supplementationStatus = [
  {
    id: 1,
    label: 'NÃO DEFINIDO',
    value: 'NÃO DEFINIDO',
  },
  {
    id: 2,
    label: 'CONCLUIDA',
    value: 'CONCLUIDA',
  },
  {
    id: 3,
    label: 'COMPRA REALIZADA',
    value: 'COMPRA REALIZADA',
  },
  {
    id: 4,
    label: 'AGUARDANDO PARECER DE ACESSO',
    value: 'AGUARDANDO PARECER DE ACESSO',
  },
  {
    id: 5,
    label: 'AGUARDANDO PAGAMENTO',
    value: 'AGUARDANDO PAGAMENTO',
  },
  {
    id: 6,
    label: 'PREDEFINIÇÃO DE EQUIPAMENTOS',
    value: 'PREDEFINIÇÃO DE EQUIPAMENTOS',
  },
]
export const contractStatus = [
  {
    id: 1,
    value: 'AGUARDANDO SOLICITAÇÃO',
    label: 'AGUARDANDO SOLICITAÇÃO',
  },
  {
    id: 2,
    value: 'SOLICITADO',
    label: 'SOLICITADO',
  },
  {
    id: 3,
    value: 'NÃO ASSINADO',
    label: 'NÃO ASSINADO',
  },
  {
    id: 4,
    value: 'ASSINADO',
    label: 'ASSINADO',
  },
  { id: 5, value: 'RESCISÃO DE CONTRATO', label: 'RESCISÃO DE CONTRATO' },
]
export const serviceTypes = [
  {
    id: 1,
    label: 'SISTEMA FOTOVOLTAICO',
    value: 'SISTEMA FOTOVOLTAICO',
  },
  {
    id: 2,
    label: 'SISTEMA FOTOVOLTAICO (OFF GRID)',
    value: 'SISTEMA FOTOVOLTAICO (OFF GRID)',
  },
  {
    id: 3,
    label: 'AUMENTO DE SISTEMA FOTOVOLTAICO',
    value: 'AUMENTO DE SISTEMA FOTOVOLTAICO',
  },
  {
    id: 4,
    label: 'BOMBA SOLAR',
    value: 'BOMBA SOLAR',
  },
  {
    id: 5,
    label: 'OPERAÇÃO E MANUTENÇÃO',
    value: 'OPERAÇÃO E MANUTENÇÃO',
  },
  {
    id: 6,
    label: 'TROCA DE PADRÃO',
    value: 'TROCA DE PADRÃO',
  },
  {
    id: 7,
    label: 'REFORMA DE PADRÃO',
    value: 'REFORMA DE PADRÃO',
  },
  {
    id: 8,
    label: 'MANUTENÇÃO CORRETIVA',
    value: 'MANUTENÇÃO CORRETIVA',
  },
  {
    id: 9,
    label: 'MANUTENÇÃO PREVENTIVA',
    value: 'MANUTENÇÃO PREVENTIVA',
  },
  {
    id: 10,
    label: 'MONTAGEM E DESMONTAGEM',
    value: 'MONTAGEM E DESMONTAGEM',
  },
  {
    id: 11,
    label: 'TROCA DE STRING BOX',
    value: 'TROCA DE STRING BOX',
  },
  {
    id: 12,
    label: 'SUBESTAÇÃO DE ENERGIA',
    value: 'SUBESTAÇÃO DE ENERGIA',
  },
]
export const allSellers = [
  {
    id: 1,
    active: true,
    label: 'ARTHUR CARVALHO',
    value: 'ARTHUR CARVALHO',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 2,
    active: true,
    label: 'ARTUR MILANE',
    value: 'ARTUR MILANE',
    qualification: 'PLENO',
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 3,
    active: false,
    label: 'CARLOS MARQUES',
    value: 'CARLOS MARQUES',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 4,
    active: true,
    label: 'DEVISSON LIMA',
    value: 'DEVISSON LIMA',
    qualification: 'JUNIOR',
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 5,
    active: true,
    label: 'DIOMAR HONORIO',
    value: 'DIOMAR HONORIO',
    qualification: 'PLENO',
    comissionAsActive: 5,
    comissionWithInside: 4,
  },
  {
    id: 6,
    active: false,
    label: 'GETULIO EDUARDO',
    value: 'GETULIO EDUARDO',
    qualification: 'PLENO',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 7,
    active: true,
    label: 'GLAIDSTONE JOSÉ',
    value: 'GLAIDSTONE JOSÉ',
    qualification: 'JUNIOR',
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 8,
    active: false,
    label: 'JESSICA PARANAIBA',
    value: 'JESSICA PARANAIBA',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 9,
    active: false,
    label: 'JORGINHO HABIB',
    value: 'JORGINHO HABIB',
    qualification: 'JUNIOR',
    comissionAsActive: 3,
    comissionWithInside: 2,
  },
  {
    id: 10,
    active: true,
    label: 'JULIANO SILVA',
    value: 'JULIANO SILVA',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 11,
    active: true,
    label: 'MATHEUS OLIVEIRA',
    value: 'MATHEUS OLIVEIRA',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 12,
    active: true,
    label: 'NEIDSON FILHO',
    value: 'NEIDSON FILHO',
    qualification: 'JUNIOR',
    comissionAsActive: 5,
    comissionWithInside: 4,
  },
  {
    id: 13,
    active: true,
    label: 'RAFAEL FEO',
    value: 'RAFAEL FEO',
    qualification: 'PLENO',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 14,
    active: false,
    label: 'ROMES ALVES',
    value: 'ROMES ALVES',
    qualification: 'PLENO',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 15,
    active: true,
    label: 'RODRIGO MORAIS',
    value: 'RODRIGO MORAIS',
    qualification: 'PLENO',
    comissionAsActive: 4,
    comissionWithInside: 3,
  },
  {
    id: 16,
    active: false,
    label: 'LUCIANO MUNIZ',
    value: 'LUCIANO MUNIZ',
    qualification: 'PLENO',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 17,
    active: true,
    label: 'DIONISIO JUNIOR',
    value: 'DIONISIO JUNIOR',
    qualification: 'PLENO',
    comissionAsActive: 5,
    comissionWithInside: 4,
  },
  {
    id: 18,
    active: true,
    label: 'LEANDRO VIALI',
    value: 'LEANDRO VIALI',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
  {
    id: 19,
    active: false,
    label: 'GUILHERME LIMA',
    value: 'GUILHERME LIMA',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 20,
    active: false,
    label: 'LUCIANO JORGE',
    value: 'LUCIANO JORGE',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 21,
    active: true,
    label: 'STENIO DE ASSIS',
    value: 'STENIO DE ASSIS',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 22,
    active: true,
    label: 'RONIVALDO MARTINS',
    value: 'RONIVALDO MARTINS',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 23,
    active: true,
    label: 'DIOGO PAULINO',
    value: 'DIOGO PAULINO',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 24,
    active: true,
    label: 'ADRIANO ARANTES',
    value: 'ADRIANO ARANTES',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 25,
    active: false,
    label: 'ARIÁDNNY APARECIDA',
    value: 'ARIÁDNNY APARECIDA',
    qualification: 'JUNIOR',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 26,
    active: false,
    label: 'DÁFINY VILLANO',
    value: 'DÁFINY VILLANO',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.9,
    comissionWithInside: 0.9,
  },
  {
    id: 27,
    active: false,
    label: 'ARTHUR ALEXANDER',
    value: 'ARTHUR ALEXANDER',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 28,
    active: false,
    label: 'FELIPE RIBEIRO',
    value: 'FELIPE RIBEIRO',
    qualification: 'INSIDE SENIOR',
    comissionAsActive: 0.25,
    comissionWithInside: 0.25,
  },
  {
    id: 29,
    active: false,
    label: 'ADAILSON COSTA',
    value: 'ADAILSON COSTA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 30,
    active: true,
    label: 'LUCIANO LOPES',
    value: 'LUCIANO LOPES',
    qualification: 'JUNIOR',
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 31,
    active: true,
    label: 'RODRIGO DE MORAIS',
    value: 'RODRIGO DE MORAIS',
    qualification: 'PLENO',
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 32,
    active: true,
    label: 'EURIPEDES JUNIOR',
    value: 'EURIPEDES JUNIOR',
    qualification: 'MASTER',
    comissionAsActive: 0,
    comissionWithInside: 0,
  },
  {
    id: 33,
    active: false,
    label: 'FRANCO MUSTAFE',
    value: 'FRANCO MUSTAFE',
    qualification: undefined,
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 34,
    active: false,
    label: 'ALLISSON OSCAR',
    value: 'ALLISSON OSCAR',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 35,
    active: undefined,
    label: 'WILLIAM MENEZES',
    value: 'WILLIAM MENEZES',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 36,
    active: false,
    label: 'MARIANA DE SOUZA',
    value: 'MARIANA DE SOUZA',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.9,
    comissionWithInside: 0.9,
  },
  {
    id: 37,
    active: false,
    label: 'CÉLIO JUNIOR',
    value: 'CÉLIO JUNIOR',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 38,
    active: true,
    label: 'THIAGO DE PAULA',
    value: 'THIAGO DE PAULA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 39,
    active: false,
    label: 'GLEITON RESENDE',
    value: 'GLEITON RESENDE',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 40,
    active: false,
    label: 'ANA PAULA PEREIRA',
    value: 'ANA PAULA PEREIRA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 41,
    active: false,
    label: 'GRASIELE DA SILVA',
    value: 'GRASIELE DA SILVA',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 42,
    active: true,
    label: 'MARCUS VINÍCIUS',
    value: 'MARCUS VINÍCIUS',
    qualification: undefined,
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 43,
    active: true,
    label: 'LEONARDO VILARINHO',
    value: 'LEONARDO VILARINHO',
    qualification: undefined,
    comissionAsActive: 1.5,
    comissionWithInside: 1,
  },
  {
    id: 44,
    active: true,
    label: 'ROBERTH JUNQUEIRA',
    value: 'ROBERTH JUNQUEIRA',
    qualification: undefined,
    comissionAsActive: 4,
    comissionWithInside: 2,
  },
  {
    id: 45,
    active: true,
    label: 'GABRIEL MARTINS',
    value: 'GABRIEL MARTINS',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 46,
    active: true,
    label: 'LUCAS FERNANDES',
    value: 'LUCAS FERNANDES',
    qualification: undefined,
    comissionAsActive: undefined,
    comissionWithInside: undefined,
  },
  {
    id: 47,
    active: true,
    label: 'GABRIEL EMANUEL',
    value: 'GABRIEL EMANUEL',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
  {
    id: 48,
    active: true,
    label: 'YASMIM ARAUJO',
    value: 'YASMIM ARAUJO',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
  {
    id: 49,
    active: true,
    label: 'RAILDO CARVALHO',
    value: 'RAILDO CARVALHO',
    qualification: undefined,
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 50,
    active: true,
    label: 'SEBASTIÃO NETO',
    value: 'SEBASTIÃO NETO',
    qualification: undefined,
    comissionAsActive: 2,
    comissionWithInside: 1,
  },
  {
    id: 51,
    active: true,
    label: 'AMANDA SANTOS',
    value: 'AMANDA SANTOS',
    qualification: 'INSIDE JUNIOR',
    comissionAsActive: 0.5,
    comissionWithInside: 0.5,
  },
]
export const insiders = allSellers.filter((s) => s.qualification?.includes('INSIDE'))
export const technicalAnalysisStatus = [
  { id: 1, label: 'CONCLUIDO', value: 'CONCLUIDO' },
  { id: 2, label: 'EM ANÁLISE TÉCNICA', value: 'EM ANÁLISE TÉCNICA' },
  {
    id: 3,
    label: 'PENDÊNCIA COMERCIAL',
    value: 'PENDÊNCIA COMERCIAL',
  },
  { id: 4, label: 'VISITA IN LOCO', value: 'VISITA IN LOCO' },
  { id: 5, label: 'REJEITADA', value: 'REJEITADA' },
  { id: 6, label: 'PENDENTE', value: 'PENDENTE' },
]
export const engineeringAnalysts = [
  {
    id: 1,
    nome: 'Andrew Borges Alexander',
    apelido: 'ANDREW',
    avatar_url:
      'https://firebasestorage.googleapis.com/v0/b/sistemaampere.appspot.com/o/usuarios%2Favatar-andrew_borges_alexander?alt=media&token=1d9787c0-7fd9-4343-9674-1ee69c03709b',
  },
  {
    id: 2,
    nome: 'Tulio Medeiros',
    apelido: 'TULIO',
    avatar_url:
      'https://firebasestorage.googleapis.com/v0/b/sistemaampere.appspot.com/o/usuarios%2Favatar-tulio_medeiros?alt=media&token=233e20b5-520d-473a-9e7e-f603a0b9493c',
  },
]
export const accessGrantingStatus = [
  {
    id: 1,
    label: 'AGUARDANDO ASSINATURA',
    value: 'AGUARDANDO ASSINATURA',
  },
  {
    id: 2,
    label: 'AGUARDANDO AUMENTO DE CARGA',
    value: 'AGUARDANDO AUMENTO DE CARGA',
  },
  { id: 3, label: 'INICIAR PROJETO', value: 'INICIAR PROJETO' },
  {
    id: 4,
    label: 'SOLICITAR TROCA DE TITULARIDADE',
    value: 'SOLICITAR TROCA DE TITULARIDADE',
  },
  {
    id: 5,
    label: 'AGUARDANDO FATURAMENTO ART',
    value: 'AGUARDANDO FATURAMENTO ART',
  },
  {
    id: 6,
    label: 'AGUARDANDO FORMULÁRIOS',
    value: 'AGUARDANDO FORMULÁRIOS',
  },
  {
    id: 7,
    label: 'AGUARDANDO RESPOSTA DA CONCESSIONARIA',
    value: 'AGUARDANDO RESPOSTA DA CONCESSIONARIA',
  },
  {
    id: 8,
    label: 'AGUARDANDO TROCA DE TITULARIDADE',
    value: 'AGUARDANDO TROCA DE TITULARIDADE',
  },
  { id: 9, label: 'AUMENTO DE CARGA', value: 'AUMENTO DE CARGA' },
  { id: 10, label: 'CANCELADO', value: 'CANCELADO' },
  {
    id: 11,
    label: 'PARECER DE ACESSO SUSPENSO',
    value: 'PARECER DE ACESSO SUSPENSO',
  },
  {
    id: 12,
    label: 'PARECER DE ACESSO APROVADO',
    value: 'PARECER DE ACESSO APROVADO',
  },
  { id: 13, label: 'PENDENCIAS', value: 'PENDENCIAS' },
  { id: 14, label: 'SOLICITAR ACESSO', value: 'SOLICITAR ACESSO' },
  {
    id: 15,
    label: 'SOLICITAR AUMENTO DE CARGA',
    value: 'SOLICITAR AUMENTO DE CARGA',
  },
  {
    id: 16,
    label: 'PARECER DE ACESSO COM OBRAS',
    value: 'PARECER DE ACESSO COM OBRAS',
  },
  {
    id: 17,
    label: 'AGUARDANDO ANÁLISE DE CARGA',
    value: 'AGUARDANDO ANÁLISE DE CARGA',
  },
  {
    id: 18,
    label: 'AGUARDANDO CORREÇÃO DE EQUIPAMENTO',
    value: 'AGUARDANDO CORREÇÃO DE EQUIPAMENTO',
  },
  { id: 19, label: 'NÃO DEFINIDO', value: 'NÃO DEFINIDO' },
]
