import { BsCart, BsFillHouseFill } from "react-icons/bs";
import { FaSolarPanel } from "react-icons/fa";
import { MdEast, MdElectricMeter, MdNorth, MdNorthEast, MdNorthWest, MdOutlineSettingsInputComponent, MdSouth, MdSouthEast, MdSouthWest, MdWest } from "react-icons/md";
import { TbTopologyFull } from "react-icons/tb";
import type { TPurchaseControl } from "./schemas/purchases";

export const ComissionableItems = ["SISTEMA", "PADRÃO", "ESTRUTURA PERSONALIZADA", "OEM", "SEGURO"];
export type TComissionableItemsEnum = "SISTEMA" | "PADRÃO" | "ESTRUTURA PERSONALIZADA" | "OEM" | "SEGURO";

export const SystemTopologiesTypes = [
	{ id: 1, label: "INVERSOR", value: "INVERSOR" },
	{ id: 2, label: "MICRO-INVERSOR", value: "MICRO-INVERSOR" },
];

export const ContractRequestPaymentOptions = [
	{
		id: 1,
		label: "70% A VISTA NA ENTRADA + 30% NA FINALIZAÇÃO DA INSTALAÇÃO",
		value: "70% A VISTA NA ENTRADA + 30% NA FINALIZAÇÃO DA INSTALAÇÃO",
		fractionnements: [
			{ title: "RECEBIMENTO DE 70% DE ENTRADA", percentage: 70 },
			{ title: "RECEBIMENTO DE 30% PÓS INSTALAÇÃO", percentage: 30 },
		],
	},
	{
		id: 2,
		label: "70% A VISTA NA ENTRADA + 15% NA FINALIZAÇÃO DA INSTALAÇÃO E 15% APÓS TROCA DO MEDIDOR",
		value: "70% A VISTA NA ENTRADA + 15% NA FINALIZAÇÃO DA INSTALAÇÃO E 15% APÓS TROCA DO MEDIDOR",
		fractionnements: [
			{ title: "RECEBIMENTO DE 70% DE ENTRADA", percentage: 70 },
			{ title: "RECEBIMENTO DE 15% PÓS INSTALAÇÃO", percentage: 15 },
			{ title: "RECEBIMENTO DE 15% PÓS TROCA DO MEDIDOR", percentage: 15 },
		],
	},
	{
		id: 3,
		label: "80% A VISTA NA ENTRADA + 20% NA FINALIZAÇÃO DA INSTALAÇÃO",
		value: "80% A VISTA NA ENTRADA + 20% NA FINALIZAÇÃO DA INSTALAÇÃO",
		fractionnements: [
			{ title: "RECEBIMENTO DE 80% DE ENTRADA", percentage: 80 },
			{ title: "RECEBIMENTO DE 20% PÓS INSTALAÇÃO", percentage: 20 },
		],
	},
	{
		id: 4,
		label: "100% A VISTA ATRAVÉS DE FINANCIAMENTO BANCÁRIO",
		value: "100% A VISTA ATRAVÉS DE FINANCIAMENTO BANCÁRIO",
		fractionnements: [{ title: "RECEBIMENTO DE 100%", percentage: 100 }],
	},
	{
		id: 5,
		label: "100% PARCELADO NO CARTÃO DE CRÉDITO",
		value: "100% PARCELADO NO CARTÃO DE CRÉDITO",
		fractionnements: [{ title: "RECEBIMENTO DE 100%", percentage: 100 }],
	},
	{
		id: 6,
		label: "100% À VISTA NO DINHEIRO/DÉBITO/PIX",
		value: "100% À VISTA NO DINHEIRO/DÉBITO/PIX",
		fractionnements: [{ title: "RECEBIMENTO DE 100%", percentage: 100 }],
	},
	{
		id: 7,
		label: "NEGOCIAÇÃO DIFERENTE (DESCREVE ABAIXO)",
		value: "NEGOCIAÇÃO DIFERENTE (DESCREVE ABAIXO)",
		fractionnements: null,
	},
	{
		id: 8,
		label: "NÃO DEFINIDO",
		value: "NÃO DEFINIDO",
		fractionnements: null,
	},
];
export const TechnicalAnalysisSolicitationTypes = [
	{
		id: 1,
		label: "ANÁLISE TÉCNICA REMOTA URBANA",
		value: "ANÁLISE TÉCNICA REMOTA URBANA",
		descriptions: [
			"Requisite uma análise técnica de instalação urbana ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações e imagens relevantes à análise.",
			"A análise pode contemplar análise de geração, sombreamento, necessidades de adequação de estrutura ou padrão de energia, etc.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 2,
		label: "ANÁLISE TÉCNICA REMOTA RURAL",
		value: "ANÁLISE TÉCNICA REMOTA RURAL",
		descriptions: [
			"Requisite uma análise técnica de instalação rural ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações e imagens relevantes à análise.",
			"A análise pode contemplar análise de geração, sombreamento, necessidades de adequação de estrutura ou padrão de energia, etc.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 3,
		label: "ANÁLISE TÉCNICA IN LOCO",
		value: "ANÁLISE TÉCNICA IN LOCO",
		descriptions: [
			"Requisite uma análise técnica in loco ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações relevantes para a visita in loco.",
			"A análise pode contemplar análise de geração, sombreamento, necessidades de adequação de estrutura ou padrão de energia, etc.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 4,
		label: "ORÇAMENTAÇÃO",
		value: "ORÇAMENTAÇÃO",
		descriptions: [
			"Requisite um orçamento de itens específicos ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para a especificação os itens a serem orçados.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 5,
		label: "DESENHO PERSONALIZADO",
		value: "DESENHO PERSONALIZADO",
		descriptions: [
			"Requisite um desenho personalizado ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações relevantes para a execução do desenho.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
];
export const TechnicalAnalysisComplexity = [
	{ id: 1, label: "SIMPLES", value: "SIMPLES" },
	{ id: 2, label: "INTERMEDIÁRIO", value: "INTERMEDIÁRIO" },
	{ id: 3, label: "COMPLEXO", value: "COMPLEXO" },
];
export const NaturalPersonMaritalStatus = [
	{ id: 1, label: "SOLTEIRO", value: "SOLTEIRO" },
	{ id: 2, label: "CASADO", value: "CASADO" },
	{ id: 3, label: "VIÚVO", value: "VIÚVO" },
	{ id: 4, label: "DIVORCIADO", value: "DIVORCIADO" },
	{ id: 5, label: "SEPERADO JURIDICAMENTE", value: "SEPERADO JURIDICAMENTE" },
];
export const VisualizationTypes = [
	{ id: 1, label: "OPERACIONAL", value: "OPERACIONAL" },
	{ id: 2, label: "EXECUÇÃO", value: "EXECUÇÃO" },
	{ id: 3, label: "VENDAS", value: "VENDAS" },
];
export const VinculationCompanies = [
	{ id: 1, label: "AMPERE ENGENHARIA E CONSULTORIA ELETRICA LTDA", value: "AMPERE ENGENHARIA E CONSULTORIA ELETRICA LTDA" },
	{ id: 2, label: "DAP CONSULTORIA INTEGRADA LTDA", value: "DAP CONSULTORIA INTEGRADA LTDA" },
];

export const InstructionLevels = [
	{ id: 1, label: "FUNDAMENTAL INCOMPLETO", value: "FUNDAMENTAL INCOMPLETO" },
	{ id: 2, label: "FUNDAMENTAL COMPLETO", value: "FUNDAMENTAL COMPLETO" },
	{ id: 3, label: "MÉDIO INCOMPLETO", value: "MÉDIO INCOMPLETO" },
	{ id: 4, label: "MÉDIO COMPLETO", value: "MÉDIO COMPLETO" },
	{ id: 5, label: "SUPERIOR INCOMPLETO", value: "SUPERIOR INCOMPLETO" },
	{ id: 6, label: "SUPERIOR COMPLETO", value: "SUPERIOR COMPLETO" },
];
export const ppsCallStatus = [
	{
		id: 1,
		label: "PENDENTE",
		value: "PENDENTE",
	},
	{
		id: 2,
		label: "EM ANDAMENTO",
		value: "EM ANDAMENTO",
	},
	{
		id: 3,
		label: "REALIZADO",
		value: "REALIZADO",
	},
];
export const supplementationStatus = [
	{ id: 1, label: "PENDENTE", value: "PENDENTE" },
	{ id: 2, label: "EM COTAÇÃO", value: "EM COTAÇÃO" },
	{ id: 3, label: "AGUARDANDO APROVAÇÃO", value: "AGUARDANDO APROVAÇÃO" },
	{ id: 4, label: "AGUARDANDO NOTA FUTURA", value: "AGUARDANDO NOTA FUTURA" },
	{ id: 5, label: "AGUARDANDO PAGAMENTO", value: "AGUARDANDO PAGAMENTO" },
	{ id: 6, label: "AGUARDANDO COMPRA", value: "AGUARDANDO COMPRA" },
	{ id: 7, label: "AGUARDANDO FATURAMENTO", value: "AGUARDANDO FATURAMENTO" },
	{ id: 8, label: "AGUARDANDO DESPACHE", value: "AGUARDANDO DESPACHE" },
	{ id: 9, label: "AGUARDANDO ENTREGA", value: "AGUARDANDO ENTREGA" },
	{ id: 10, label: "PENDÊNCIAS", value: "PENDÊNCIAS" },
	{ id: 11, label: "CONCLUÍDA", value: "CONCLUÍDA" },
];
export const contractStatus = [
	{
		id: 1,
		value: "AGUARDANDO SOLICITAÇÃO",
		label: "AGUARDANDO SOLICITAÇÃO",
	},
	{
		id: 2,
		value: "SOLICITADO",
		label: "SOLICITADO",
	},
	{
		id: 3,
		value: "NÃO ASSINADO",
		label: "NÃO ASSINADO",
	},
	{
		id: 4,
		value: "ASSINADO",
		label: "ASSINADO",
	},
	{ id: 5, value: "RESCISÃO DE CONTRATO", label: "RESCISÃO DE CONTRATO" },
];
export const serviceTypes = [
	{
		id: 1,
		label: "SISTEMA FOTOVOLTAICO",
		value: "SISTEMA FOTOVOLTAICO",
	},
	{
		id: 2,
		label: "SISTEMA FOTOVOLTAICO (OFF GRID)",
		value: "SISTEMA FOTOVOLTAICO (OFF GRID)",
	},
	{
		id: 3,
		label: "AUMENTO DE SISTEMA FOTOVOLTAICO",
		value: "AUMENTO DE SISTEMA FOTOVOLTAICO",
	},
	{
		id: 4,
		label: "BOMBA SOLAR",
		value: "BOMBA SOLAR",
	},
	{
		id: 5,
		label: "OPERAÇÃO E MANUTENÇÃO",
		value: "OPERAÇÃO E MANUTENÇÃO",
	},
	{
		id: 6,
		label: "TROCA DE PADRÃO",
		value: "TROCA DE PADRÃO",
	},
	{
		id: 7,
		label: "REFORMA DE PADRÃO",
		value: "REFORMA DE PADRÃO",
	},
	{
		id: 8,
		label: "MANUTENÇÃO CORRETIVA",
		value: "MANUTENÇÃO CORRETIVA",
	},
	{
		id: 9,
		label: "MANUTENÇÃO PREVENTIVA",
		value: "MANUTENÇÃO PREVENTIVA",
	},
	{
		id: 10,
		label: "MONTAGEM E DESMONTAGEM",
		value: "MONTAGEM E DESMONTAGEM",
	},
	{
		id: 11,
		label: "TROCA DE STRING BOX",
		value: "TROCA DE STRING BOX",
	},
	{
		id: 12,
		label: "SUBESTAÇÃO DE ENERGIA",
		value: "SUBESTAÇÃO DE ENERGIA",
	},
	{
		id: 13,
		label: "HOMOLOGAÇÃO",
		value: "HOMOLOGAÇÃO",
	},
	{
		id: 14,
		label: "SEGURO DE SISTEMA FOTOVOLTAICO",
		value: "SEGURO DE SISTEMA FOTOVOLTAICO",
	},
	{
		id: 15,
		label: "PRODUTOS",
		value: "PRODUTOS",
	},
	{
		id: 16,
		label: "CONSÓRCIO DE ENERGIA",
		value: "CONSÓRCIO DE ENERGIA",
	},
	{
		id: 17,
		label: "MONITORAMENTO",
		value: "MONITORAMENTO",
	},
	{
		id: 18,
		label: "PRODUTOS E SERVIÇOS AVULSOS",
		value: "PRODUTOS E SERVIÇOS AVULSOS",
	},
];
export const allSellers = [
	{
		id: 1,
		active: false,
		label: "ADAILSON COSTA",
		value: "ADAILSON COSTA",
	},
	{
		id: 2,
		active: true,
		label: "ADRIANA FRANÇOISE",
		value: "ADRIANA FRANÇOISE",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 3,
		active: true,
		label: "ADRIANO ARANTES",
		value: "ADRIANO ARANTES",
		qualification: "JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 4,
		active: false,
		label: "ALLISSON OSCAR",
		value: "ALLISSON OSCAR",
	},
	{
		id: 5,
		active: true,
		label: "AMANDA SANTOS",
		value: "AMANDA SANTOS",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 6,
		active: false,
		label: "ANA PAULA PEREIRA",
		value: "ANA PAULA PEREIRA",
	},
	{
		id: 7,
		active: false,
		label: "ARIÁDNNY APARECIDA",
		value: "ARIÁDNNY APARECIDA",
		qualification: "JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 8,
		active: false,
		label: "ARTHUR ALEXANDER",
		value: "ARTHUR ALEXANDER",
	},
	{
		id: 9,
		active: true,
		label: "ARTHUR CARVALHO",
		value: "ARTHUR CARVALHO",
		qualification: "MASTER",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 10,
		active: true,
		label: "ARTUR MILANE",
		value: "ARTUR MILANE",
		qualification: "PLENO",
		comissionAsActive: 2,
		comissionWithInside: 1,
	},
	{
		id: 11,
		active: true,
		label: "BRUNO PEREIRA",
		value: "BRUNO PEREIRA",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 12,
		active: false,
		label: "CARLOS MARQUES",
		value: "CARLOS MARQUES",
		qualification: "JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 13,
		active: false,
		label: "CÉLIO JUNIOR",
		value: "CÉLIO JUNIOR",
	},
	{
		id: 14,
		active: false,
		label: "DÁFINY VILLANO",
		value: "DÁFINY VILLANO",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.9,
		comissionWithInside: 0.9,
	},
	{
		id: 15,
		active: true,
		label: "DEBORA CRISTINA",
		value: "DEBORA CRISTINA",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 16,
		active: true,
		label: "DEVISSON LIMA",
		value: "DEVISSON LIMA",
		qualification: "JUNIOR",
		comissionAsActive: 2,
		comissionWithInside: 1,
	},
	{
		id: 17,
		active: true,
		label: "DIOGO PAULINO",
		value: "DIOGO PAULINO",
		qualification: "MASTER",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 18,
		active: true,
		label: "DIOMAR HONORIO",
		value: "DIOMAR HONORIO",
		qualification: "PLENO",
		comissionAsActive: 5,
		comissionWithInside: 4,
	},
	{
		id: 19,
		active: true,
		label: "DIONISIO CARVALHO",
		value: "DIONISIO CARVALHO",
		qualification: "PLENO",
		comissionAsActive: 5,
		comissionWithInside: 4,
	},
	{
		id: 20,
		active: true,
		label: "ELISANGELA VIEIRA",
		value: "ELISANGELA VIEIRA",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 21,
		active: true,
		label: "EURIPEDES JUNIOR",
		value: "EURIPEDES JUNIOR",
		qualification: "MASTER",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 22,
		active: true,
		label: "FELIPE NOBREGA",
		value: "FELIPE NOBREGA",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 23,
		active: false,
		label: "FELIPE RIBEIRO",
		value: "FELIPE RIBEIRO",
		qualification: "INSIDE SENIOR",
		comissionAsActive: 0.25,
		comissionWithInside: 0.25,
	},
	{
		id: 24,
		active: true,
		label: "FELIPE TADEU",
		value: "FELIPE TADEU",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 25,
		active: false,
		label: "FRANCO MUSTAFE",
		value: "FRANCO MUSTAFE",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 26,
		active: true,
		label: "GABRIEL EMANUEL",
		value: "GABRIEL EMANUEL",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 27,
		active: true,
		label: "GABRIEL MARTINS",
		value: "GABRIEL MARTINS",
	},
	{
		id: 28,
		active: false,
		label: "GETULIO EDUARDO",
		value: "GETULIO EDUARDO",
		qualification: "PLENO",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 29,
		active: true,
		label: "GLAIDSTONE JOSÉ",
		value: "GLAIDSTONE JOSÉ",
		qualification: "JUNIOR",
		comissionAsActive: 2,
		comissionWithInside: 1,
	},
	{
		id: 30,
		active: false,
		label: "GLEITON RESENDE",
		value: "GLEITON RESENDE",
	},
	{
		id: 31,
		active: false,
		label: "GRASIELE DA SILVA",
		value: "GRASIELE DA SILVA",
	},
	{
		id: 32,
		active: false,
		label: "GUILHERME LIMA",
		value: "GUILHERME LIMA",
		qualification: "JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 33,
		active: false,
		label: "JESSICA PARANAIBA",
		value: "JESSICA PARANAIBA",
		qualification: "JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 34,
		active: false,
		label: "JORGINHO HABIB",
		value: "JORGINHO HABIB",
		qualification: "JUNIOR",
		comissionAsActive: 3,
		comissionWithInside: 2,
	},
	{
		id: 35,
		active: true,
		label: "JOSÉ ROBERTO",
		value: "JOSÉ ROBERTO",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 36,
		active: true,
		label: "JULIANO SILVA",
		value: "JULIANO SILVA",
		qualification: "JUNIOR",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 37,
		active: true,
		label: "LAYANE FERNANDA",
		value: "LAYANE FERNANDA",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 38,
		active: true,
		label: "LEANDRO VIALI",
		value: "LEANDRO VIALI",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 39,
		active: true,
		label: "LEONARDO VILARINHO",
		value: "LEONARDO VILARINHO",
		comissionAsActive: 1.5,
		comissionWithInside: 1,
	},
	{
		id: 40,
		active: true,
		label: "LUCAS FERNANDES",
		value: "LUCAS FERNANDES",
	},
	{
		id: 41,
		active: false,
		label: "LUCIANO JORGE",
		value: "LUCIANO JORGE",
		qualification: "JUNIOR",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 42,
		active: true,
		label: "LUCIANO LOPES",
		value: "LUCIANO LOPES",
		qualification: "JUNIOR",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 43,
		active: false,
		label: "LUCIANO MUNIZ",
		value: "LUCIANO MUNIZ",
		qualification: "PLENO",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 44,
		active: true,
		label: "MARCUS VINÍCIUS",
		value: "MARCUS VINÍCIUS",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 45,
		active: false,
		label: "MARIANA DE SOUZA",
		value: "MARIANA DE SOUZA",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.9,
		comissionWithInside: 0.9,
	},
	{
		id: 46,
		active: true,
		label: "MATHEUS OLIVEIRA",
		value: "MATHEUS OLIVEIRA",
		qualification: "MASTER",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 47,
		active: true,
		label: "NEIDSON FILHO",
		value: "NEIDSON FILHO",
		qualification: "JUNIOR",
		comissionAsActive: 5,
		comissionWithInside: 4,
	},
	{
		id: 48,
		active: false,
		label: "PEDRO ALMEIDA",
		value: "PEDRO ALMEIDA",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 49,
		active: true,
		label: "RAFAEL FEO",
		value: "RAFAEL FEO",
		qualification: "PLENO",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 50,
		active: true,
		label: "RAILDO CARVALHO",
		value: "RAILDO CARVALHO",
		comissionAsActive: 2,
		comissionWithInside: 1,
	},
	{
		id: 51,
		active: true,
		label: "ROBERTH JUNQUEIRA",
		value: "ROBERTH JUNQUEIRA",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 52,
		active: true,
		label: "RODRIGO DE MORAIS",
		value: "RODRIGO DE MORAIS",
		qualification: "PLENO",
	},
	{
		id: 53,
		active: true,
		label: "RODRIGO MORAIS",
		value: "RODRIGO MORAIS",
		qualification: "PLENO",
		comissionAsActive: 4,
		comissionWithInside: 3,
	},
	{
		id: 54,
		active: false,
		label: "ROMES ALVES",
		value: "ROMES ALVES",
		qualification: "PLENO",
		comissionAsActive: 0,
		comissionWithInside: 0,
	},
	{
		id: 55,
		active: true,
		label: "RONIVALDO MARTINS",
		value: "RONIVALDO MARTINS",
		qualification: "JUNIOR",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 56,
		active: true,
		label: "SEBASTIÃO NETO",
		value: "SEBASTIÃO NETO",
		comissionAsActive: 2,
		comissionWithInside: 1,
	},
	{
		id: 57,
		active: true,
		label: "STENIO DE ASSIS",
		value: "STENIO DE ASSIS",
		qualification: "JUNIOR",
		comissionAsActive: 4,
		comissionWithInside: 2,
	},
	{
		id: 58,
		active: true,
		label: "THIAGO DE PAULA",
		value: "THIAGO DE PAULA",
	},
	{
		id: 59,
		label: "WILLIAM MENEZES",
		value: "WILLIAM MENEZES",
	},
	{
		id: 60,
		active: true,
		label: "YASMIM ARAUJO",
		value: "YASMIM ARAUJO",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 61,
		active: true,
		label: "ALESSANDER IDALECIO",
		value: "ALESSANDER IDALECIO",
		qualification: "INSIDE PLENO",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 62,
		active: true,
		label: "ANA BEATRIZ",
		value: "ANA BEATRIZ",
		qualification: "",
		comissionAsActive: 1,
		comissionWithInside: 1,
	},
	{
		id: 63,
		active: true,
		label: "DANDARA LINA",
		value: "DANDARA LINA",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 64,
		active: true,
		label: "ADÃO FERRAZ",
		value: "ADÃO FERRAZ",
		qualification: "",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 65,
		active: true,
		label: "LEONARDO VITAL",
		value: "LEONARDO VITAL",
		qualification: "INSIDE JUNIOR",
		comissionAsActive: 0.5,
		comissionWithInside: 0.5,
	},
	{
		id: 66,
		active: true,
		label: "DANIELA FRANCISCA",
		value: "DANIELA FRANCISCA",
		qualification: "",
		comissionAsActive: 1,
		comissionWithInside: 1,
	},
	{
		id: 67,
		active: true,
		label: "ROBSON VARGAS",
		value: "ROBSON VARGAS",
		qualification: "",
		comissionAsActive: 1,
		comissionWithInside: 1,
	},
	{
		id: 68,
		active: true,
		label: "JOÃO PEDRO",
		value: "JOÃO PEDRO",
		qualification: "",
		comissionAsActive: 1,
		comissionWithInside: 1,
	},
	{
		id: 69,
		active: true,
		label: "LUIZ PAULO",
		value: "LUIZ PAULO",
		qualification: "",
		comissionAsActive: 1,
		comissionWithInside: 1,
	},
].sort((a, b) => a.value.localeCompare(b.value));
export const insiders = allSellers.filter((s) => s.qualification?.includes("INSIDE"));
export const allActiveSellers = allSellers.filter((s) => s.active);
export const billableCompanies = [
	{ id: 1, label: "AMPERE ENERGIAS", value: "AMPERE ENERGIAS" },
	{ id: 2, label: "IZAIRA SERVIÇOS", value: "IZAIRA SERVIÇOS" },
	{ id: 3, label: "SYNERGIA", value: "SYNERGIA" },
	{ id: 4, label: "ANALISE DO FINANCEIRO", value: "ANALISE DO FINANCEIRO" },
	{ id: 5, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
];
export const technicalAnalysisStatus = [
	{ id: 1, label: "CONCLUIDO", value: "CONCLUIDO" },
	{ id: 2, label: "EM ANÁLISE TÉCNICA", value: "EM ANÁLISE TÉCNICA" },
	{ id: 3, label: "PENDÊNCIA COMERCIAL", value: "PENDÊNCIA COMERCIAL" },
	{ id: 4, label: "PENDÊNCIA OPERACIONAL", value: "PENDÊNCIA OPERACIONAL" },
	{ id: 5, label: "REJEITADA", value: "REJEITADA" },
	{ id: 6, label: "PENDENTE", value: "PENDENTE" },
];
export const technicalAnalysisSolicitationTypes = [
	{
		id: 1,
		label: "ANÁLISE TÉCNICA REMOTA URBANA",
		value: "ANÁLISE TÉCNICA REMOTA URBANA",
		descriptions: [
			"Requisite uma análise técnica de instalação urbana ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações e imagens relevantes à análise.",
			"A análise pode contemplar análise de geração, sombreamento, necessidades de adequação de estrutura ou padrão de energia, etc.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 2,
		label: "ANÁLISE TÉCNICA REMOTA RURAL",
		value: "ANÁLISE TÉCNICA REMOTA RURAL",
		descriptions: [
			"Requisite uma análise técnica de instalação rural ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações e imagens relevantes à análise.",
			"A análise pode contemplar análise de geração, sombreamento, necessidades de adequação de estrutura ou padrão de energia, etc.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 3,
		label: "ANÁLISE TÉCNICA IN LOCO",
		value: "ANÁLISE TÉCNICA IN LOCO",
		descriptions: [
			"Requisite uma análise técnica in loco ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações relevantes para a visita in loco.",
			"A análise pode contemplar análise de geração, sombreamento, necessidades de adequação de estrutura ou padrão de energia, etc.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 4,
		label: "ORÇAMENTAÇÃO",
		value: "ORÇAMENTAÇÃO",
		descriptions: [
			"Requisite um orçamento de itens específicos ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para a especificação os itens a serem orçados.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
	{
		id: 5,
		label: "DESENHO PERSONALIZADO",
		value: "DESENHO PERSONALIZADO",
		descriptions: [
			"Requisite um desenho personalizado ao nosso time de analistas.",
			"Clicando aqui, você prosseguirá para um formulário para a coleta de informações relevantes para a execução do desenho.",
			"O prazo de análise é de até 72 horas úteis.",
		],
	},
];
export const technicalAnalysisPendencyCategories = [
	{ id: 1, label: "PENDÊNCIA COMERCIAL", value: "PENDÊNCIA COMERCIAL" },
	{ id: 2, label: "PENDÊNCIA TERCEIROS", value: "PENDÊNCIA TERCEIROS" }, // COTAÇÕES, ETC
	{ id: 3, label: "PENDÊNCIA CONCESSIONÁRIA", value: "PENDÊNCIA CONCESSIONÁRIA" },
	{ id: 4, label: "OUTROS", value: "OUTROS" },
];
export const engineeringAnalysts = [
	{
		id: 1,
		nome: "Andrew Borges Alexander",
		apelido: "ANDREW",
		avatar_url:
			"https://firebasestorage.googleapis.com/v0/b/sistemaampere.appspot.com/o/usuarios%2Favatar-andrew_borges_alexander?alt=media&token=1d9787c0-7fd9-4343-9674-1ee69c03709b",
	},
	{
		id: 2,
		nome: "Tulio Medeiros",
		apelido: "TULIO",
		avatar_url: "https://firebasestorage.googleapis.com/v0/b/sistemaampere.appspot.com/o/usuarios%2Favatar-tulio_medeiros?alt=media&token=233e20b5-520d-473a-9e7e-f603a0b9493c",
	},
];
export const accessGrantingStatus = [
	{
		id: 1,
		label: "AGUARDANDO ASSINATURA",
		value: "AGUARDANDO ASSINATURA",
	},
	{
		id: 2,
		label: "AGUARDANDO AUMENTO DE CARGA",
		value: "AGUARDANDO AUMENTO DE CARGA",
	},
	{
		id: 3,
		label: "SOLICITAR TROCA DE TITULARIDADE",
		value: "SOLICITAR TROCA DE TITULARIDADE",
	},
	{
		id: 3,
		label: "AGUARDANDO FATURAMENTO ART",
		value: "AGUARDANDO FATURAMENTO ART",
	},
	{
		id: 4,
		label: "AGUARDANDO RESPOSTA DA CONCESSIONARIA",
		value: "AGUARDANDO RESPOSTA DA CONCESSIONARIA",
	},
	{
		id: 5,
		label: "AGUARDANDO TROCA DE TITULARIDADE",
		value: "AGUARDANDO TROCA DE TITULARIDADE",
	},
	{
		id: 6,
		label: "PARECER DE ACESSO SUSPENSO",
		value: "PARECER DE ACESSO SUSPENSO",
	},
	{
		id: 7,
		label: "PARECER DE ACESSO APROVADO",
		value: "PARECER DE ACESSO APROVADO",
	},
	{ id: 8, label: "PENDENCIAS", value: "PENDENCIAS" },
	{
		id: 9,
		label: "PARECER DE ACESSO COM OBRAS",
		value: "PARECER DE ACESSO COM OBRAS",
	},
	{
		id: 10,
		label: "AGUARDANDO ANÁLISE DE CARGA",
		value: "AGUARDANDO ANÁLISE DE CARGA",
	},
	{
		id: 11,
		label: "AGUARDANDO CORREÇÃO DE EQUIPAMENTO",
		value: "AGUARDANDO CORREÇÃO DE EQUIPAMENTO",
	},
	{
		id: 12,
		label: "PARECER APROVADO - NOTURNO",
		value: "PARECER APROVADO - NOTURNO",
	},
	{
		id: 13,
		label: "PENDÊNCIAS - DÉBITOS",
		value: "PENDÊNCIAS - DÉBITOS",
	},
	{ id: 14, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
];
export const executionStatus = [
	{ id: 1, label: "AGENDADA", value: "AGENDADA" },
	{ id: 2, label: "AGUARDANDO AGENDAMENTO", value: "AGUARDANDO AGENDAMENTO" },
	{ id: 3, label: "CONCLUIDA", value: "CONCLUIDA" },
	{ id: 4, label: "CONCLUIDA PARCIAL", value: "CONCLUIDA PARCIAL" },
	{ id: 5, label: "EM ANDAMENTO", value: "EM ANDAMENTO" },
	{ id: 6, label: "OBRA CANCELADA", value: "OBRA CANCELADA" },
	{ id: 7, label: "CASA EM CONSTRUÇÃO", value: "CASA EM CONSTRUÇÃO" },
	{ id: 8, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
];
export const inspectionStatus = [
	{ id: 1, label: "REALIZADA", value: "REALIZADA" },
	{ id: 2, label: "AGUARDANDO OBRA DE REDE", value: "AGUARDANDO OBRA DE REDE" },
	{ id: 3, label: "AGUARDANDO CONCESSIONARIA", value: "AGUARDANDO CONCESSIONARIA" },
	{ id: 4, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
];
export const reliabilityAnalysts = [
	{ id: 1, value: "POLLIANA CRISTINA DE REZENDE", label: "POLLIANA", cod: 1 },
	{ id: 2, value: "ALINE APARECIDA RODRIGUES CARVALHO", label: "ALINE", cod: 21 },
	{ id: 3, value: "ANDREW BORGES ALEXANDER", label: "ANDREW", cod: 44 },
	{ id: 4, value: "JORDANA ALVES DE FREITAS", label: "JORDANA", cod: 29 },
	{ id: 5, value: "ANDRIELLY GARCIA DOS SANTOS MARQUES", label: "ANDRIELLY", cod: 51 },
	{ id: 6, value: "GLENDA ELIAS NASCIMENTO SANTOS", label: "GLENDA", cod: 52 },
	{ id: 7, value: "TULIO HENRIQUE SILVA MEDEIROS", label: "TULIO", cod: 53 },
	{ id: 8, value: "EDUARDO HENRIQUE DOMINGOS DE MORAES", label: "EDUARDO", cod: 54 },
	{ id: 9, value: "LAZARO MARQUES", label: "LAZARO", cod: 55 },
	{ id: 10, value: "NÃO DEFINIDO", label: "NÃO DEFINIDO", cod: 0 },
];
export const customersAcquisitionChannels = [
	{ id: 1, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
	{ id: 2, label: "NETWORK", value: "NETWORK" },
	{ id: 3, label: "INSIDE SALES", value: "INSIDE SALES" },
	{ id: 4, label: "INDICAÇÃO DE AMIGO", value: "INDICAÇÃO DE AMIGO" },
	{ id: 5, label: "CALCULADORA SOLAR", value: "CALCULADORA SOLAR" },
	{ id: 6, label: "GOOGLE ADS", value: "GOOGLE ADS" },
	{ id: 7, label: "FACEBOOK ADS", value: "FACEBOOK ADS" },
	{ id: 8, label: "PORTA A PORTA", value: "PORTA A PORTA" },
	{ id: 9, label: "TELEVENDAS", value: "TELEVENDAS" },
	{ id: 10, label: "EVENTO", value: "EVENTO" },
	{ id: 11, label: "PASSIVO", value: "PASSIVO" },
	{ id: 12, label: "PROSPECÇÃO ATIVA", value: "PROSPECÇÃO ATIVA" },
];
export const additionalCostsCategories = [
	{
		id: 1,
		label: "INSTALAÇÃO",
		value: "INSTALAÇÃO",
	},
	{
		id: 2,
		label: "PADRÃO",
		value: "PADRÃO",
	},
	{
		id: 3,
		label: "ESTRUTURA",
		value: "ESTRUTURA",
	},
	{
		id: 4,
		label: "OUTROS",
		value: "OUTROS",
	},
];
export const units = [
	{ id: 1, label: "UNIDADE (UN)", value: "UN" },
	{ id: 2, label: "PACOTE (PC)", value: "PC" },
	{ id: 3, label: "QUILO (KG)", value: "KG" },
	{ id: 4, label: "CX (CAIXA)", value: "CX" },
	{ id: 5, label: "M (METRO)", value: "M" },
	{ id: 6, label: "METRO QUADRADO (M²)", value: "M²" },
	{ id: 7, label: "METRO CÚBICO (M³)", value: "M³" },
	{ id: 8, label: "LITROS (L)", value: "L" },
	{ id: 9, label: "MESA", value: "MESA" },
];
export const journeyPendings = [
	{ id: 1, label: "PENDENTE BOAS VINDAS", value: "boasVindas" },
	{ id: 2, label: "PENDENTE ASS.DOCUMENTOS", value: "assDocumentacoes" },
	{ id: 3, label: "PENDENTE COMPRA DO KIT", value: "compraDoKit" },
	{ id: 4, label: "PENDENTE NF FATURADA", value: "nfFaturada" },
	{ id: 5, label: "PENDENTE PREV. ENTREGA", value: "prevChegada" },
	{ id: 6, label: "PENDENTE RESP.CONCESSIONÁRIA", value: "respConcessionaria" },
	{ id: 7, label: "PENDENTE ENTREGA DO KIT", value: "entregaDoKit" },
	{ id: 8, label: "PENDENTE INSTALAÇÃO AGENDADA", value: "instalacaoAgendada" },
	{ id: 9, label: "PENDENTE INSTALAÇÃO REALIZADA", value: "instalacaoRealizada" },
	{ id: 10, label: "PENDENTE VISTORIA", value: "vistoriaConcessionaria" },
	{ id: 11, label: "PENDENTE SISTEMA LIGADO", value: "sistemaLigado" },
	{ id: 12, label: "PENDENTE ENTREGA TÉCNICA", value: "entregaTecnica" },
	{ id: 13, label: "JORNADA NÃO CONCLUÍDA", value: "jornadaConcluida" },
];
export const deliveryStatus = [
	{ id: 1, label: "AGUARDANDO COMPRA", value: "AGUARDANDO COMPRA" },
	{ id: 2, label: "EM ROTA", value: "EM ROTA" },
	{ id: 3, label: "ENTREGUE", value: "ENTREGUE" },
	{ id: 4, label: "CANCELADO", value: "CANCELADO" },
	{ id: 5, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
];
export const ProductItemCategories = [
	{ id: 1, label: "MÓDULO", value: "MÓDULO", icon: FaSolarPanel as React.ComponentType },
	{ id: 2, label: "INVERSOR", value: "INVERSOR", icon: TbTopologyFull as React.ComponentType },
	{ id: 3, label: "INSUMO", value: "INSUMO", icon: MdOutlineSettingsInputComponent as React.ComponentType },
	{ id: 4, label: "ESTRUTURA", value: "ESTRUTURA", icon: BsFillHouseFill as React.ComponentType },
	{ id: 5, label: "PADRÃO", value: "PADRÃO", icon: MdElectricMeter as React.ComponentType },
	{ id: 6, label: "OUTROS", value: "OUTROS", icon: BsCart as React.ComponentType },
];
export const SigningForms = [
	{ id: 1, label: "FÍSICA", value: "FÍSICA" },
	{ id: 2, label: "DIGITAL", value: "DIGITAL" },
];
export const EnergyDistributorsOptions = [
	{ id: 1, label: "AME", value: "AME" },
	{ id: 2, label: "BOA VISTA", value: "BOA VISTA" },
	{ id: 3, label: "CASTRO -DIS", value: "CASTRO -DIS" },
	{ id: 4, label: "CEA", value: "CEA" },
	{ id: 5, label: "CEBDIS", value: "CEBDIS" },
	{ id: 6, label: "CEDRAP", value: "CEDRAP" },
	{ id: 7, label: "CEDRI", value: "CEDRI" },
	{ id: 8, label: "CEEE-D", value: "CEEE-D" },
	{ id: 9, label: "CEGERO", value: "CEGERO" },
	{ id: 10, label: "CEJAMA", value: "CEJAMA" },
	{ id: 11, label: "CELESC-DIS", value: "CELESC-DIS" },
	{ id: 12, label: "CELETRO", value: "CELETRO" },
	{ id: 13, label: "CELPE", value: "CELPE" },
	{ id: 14, label: "CEMIG D", value: "CEMIG D" },
	{ id: 15, label: "CEMIRIM", value: "CEMIRIM" },
	{ id: 16, label: "CEPRAG", value: "CEPRAG" },
	{ id: 17, label: "CERA ÇÁ", value: "CERA ÇÁ" },
	{ id: 18, label: "CERAL ANIT ÁPOLIS", value: "CERAL ANIT ÁPOLIS" },
	{ id: 19, label: "CERAL ARAPOTI", value: "CERAL ARAPOTI" },
	{ id: 20, label: "CERAL ARARUAMA", value: "CERAL ARARUAMA" },
	{ id: 21, label: "CERBRANORTE", value: "CERBRANORTE" },
	{ id: 22, label: "CERCI", value: "CERCI" },
	{ id: 23, label: "CERCOS", value: "CERCOS" },
	{ id: 24, label: "CEREJ", value: "CEREJ" },
	{ id: 25, label: "CERES", value: "CERES" },
	{ id: 26, label: "CERFOX", value: "CERFOX" },
	{ id: 27, label: "CERGAL", value: "CERGAL" },
	{ id: 28, label: "CERGAPA", value: "CERGAPA" },
	{ id: 29, label: "CERGRAL", value: "CERGRAL" },
	{ id: 30, label: "CERILUZ", value: "CERILUZ" },
	{ id: 31, label: "CERIM", value: "CERIM" },
	{ id: 32, label: "CERIPA", value: "CERIPA" },
	{ id: 33, label: "CERIS", value: "CERIS" },
	{ id: 34, label: "CERMC", value: "CERMC" },
	{ id: 35, label: "CERMISS ÕES", value: "CERMISS ÕES" },
	{ id: 36, label: "CERMOFUL", value: "CERMOFUL" },
	{ id: 37, label: "CERNHE", value: "CERNHE" },
	{ id: 38, label: "CERON", value: "CERON" },
	{ id: 39, label: "CERPALO", value: "CERPALO" },
	{ id: 40, label: "CERPRO", value: "CERPRO" },
	{ id: 41, label: "CERR", value: "CERR" },
	{ id: 42, label: "CERRP", value: "CERRP" },
	{ id: 43, label: "CERSAD DISTRIBUIDORA", value: "CERSAD DISTRIBUIDORA" },
	{ id: 44, label: "CERSUL", value: "CERSUL" },
	{ id: 45, label: "CERTAJA", value: "CERTAJA" },
	{ id: 46, label: "CERTEL ENERGIA", value: "CERTEL ENERGIA" },
	{ id: 47, label: "CERTHIL", value: "CERTHIL" },
	{ id: 48, label: "CERTREL", value: "CERTREL" },
	{ id: 49, label: "CERVAM", value: "CERVAM" },
	{ id: 50, label: "CETRIL", value: "CETRIL" },
	{ id: 51, label: "CFLO", value: "CFLO" },
	{ id: 52, label: "CHESP", value: "CHESP" },
	{ id: 53, label: "CNEE", value: "CNEE" },
	{ id: 54, label: "COCEL", value: "COCEL" },
	{ id: 55, label: "CODESAM", value: "CODESAM" },
	{ id: 56, label: "COELBA", value: "COELBA" },
	{ id: 57, label: "COOPERA", value: "COOPERA" },
	{ id: 58, label: "COOPERALIAN ÇA", value: "COOPERALIAN ÇA" },
	{ id: 59, label: "COOPERCOCAL", value: "COOPERCOCAL" },
	{ id: 60, label: "COOPERLUZ", value: "COOPERLUZ" },
	{ id: 61, label: "COOPERMILA", value: "COOPERMILA" },
	{ id: 62, label: "COOPERNORTE", value: "COOPERNORTE" },
	{ id: 63, label: "COOPERSUL", value: "COOPERSUL" },
	{ id: 64, label: "COOPERZEM", value: "COOPERZEM" },
	{ id: 65, label: "COORSEL", value: "COORSEL" },
	{ id: 66, label: "COPEL-DIS", value: "COPEL-DIS" },
	{ id: 67, label: "COPREL", value: "COPREL" },
	{ id: 68, label: "COSERN", value: "COSERN" },
	{ id: 69, label: "CPFL JAGUARI", value: "CPFL JAGUARI" },
	{ id: 70, label: "CPFL LESTE PAULISTA", value: "CPFL LESTE PAULISTA" },
	{ id: 71, label: "CPFL MOCOCA", value: "CPFL MOCOCA" },
	{ id: 72, label: "CPFL SANTA CRUZ", value: "CPFL SANTA CRUZ" },
	{ id: 73, label: "CPFL SUL PAULISTA", value: "CPFL SUL PAULISTA" },
	{ id: 74, label: "CPFL-PIRATININGA", value: "CPFL-PIRATININGA" },
	{ id: 75, label: "CPFL-PAULISTA", value: "CPFL-PAULISTA" },
	{ id: 76, label: "CRELUZ-D", value: "CRELUZ-D" },
	{ id: 77, label: "CRERAL", value: "CRERAL" },
	{ id: 78, label: "DCELT", value: "DCELT" },
	{ id: 79, label: "DEMEI", value: "DEMEI" },
	{ id: 80, label: "DMED", value: "DMED" },
	{ id: 81, label: "EBO", value: "EBO" },
	{ id: 82, label: "EDEVP", value: "EDEVP" },
	{ id: 83, label: "EDP ES", value: "EDP ES" },
	{ id: 84, label: "EDP SP", value: "EDP SP" },
	{ id: 85, label: "EEB", value: "EEB" },
	{ id: 86, label: "EFLJC", value: "EFLJC" },
	{ id: 87, label: "EFLUL", value: "EFLUL" },
	{ id: 88, label: "ELEKTRO", value: "ELEKTRO" },
	{ id: 89, label: "ELETROACRE", value: "ELETROACRE" },
	{ id: 90, label: "ELETROCAR", value: "ELETROCAR" },
	{ id: 91, label: "ELETROPAULO", value: "ELETROPAULO" },
	{ id: 92, label: "ELFSM", value: "ELFSM" },
	{ id: 93, label: "EMR", value: "EMR" },
	{ id: 94, label: "ENERGISA MS", value: "ENERGISA MS" },
	{ id: 95, label: "ENERGISA MT", value: "ENERGISA MT" },
	{ id: 96, label: "ENEL CE", value: "ENEL CE" },
	{ id: 97, label: "ENEL RJ", value: "ENEL RJ" },
	{ id: 98, label: "ENF", value: "ENF" },
	{ id: 99, label: "EPB", value: "EPB" },
	{ id: 100, label: "EQUATORIAL AL", value: "EQUATORIAL AL" },
	{ id: 101, label: "EQUATORIAL GO", value: "EQUATORIAL GO" },
	{ id: 102, label: "EQUATORIAL MA", value: "EQUATORIAL MA" },
	{ id: 103, label: "EQUATORIAL PA", value: "EQUATORIAL PA" },
	{ id: 104, label: "EQUATORIAL PI", value: "EQUATORIAL PI" },
	{ id: 105, label: "ESE", value: "ESE" },
	{ id: 106, label: "ESS", value: "ESS" },
	{ id: 107, label: "ETO", value: "ETO" },
	{ id: 108, label: "HIDROPAN", value: "HIDROPAN" },
	{ id: 109, label: "LIGHT", value: "LIGHT" },
	{ id: 110, label: "MUXENERGIA", value: "MUXENERGIA" },
	{ id: 111, label: "PACTO ENERGIA PR", value: "PACTO ENERGIA PR" },
	{ id: 112, label: "RGE", value: "RGE" },
	{ id: 113, label: "RGE SUL", value: "RGE SUL" },
	{ id: 114, label: "SULGIPE", value: "SULGIPE" },
	{ id: 115, label: "UHENPAL", value: "UHENPAL" },
] as const;
export const HomologationControlStatus = [
	{ id: 1, label: "PENDENTE", value: "PENDENTE" },
	{ id: 2, label: "CANCELADO", value: "CANCELADO" },
	{ id: 3, label: "ELABORANDO DOCUMENTAÇÕES", value: "ELABORANDO DOCUMENTAÇÕES" },
	{ id: 4, label: "AGUARDANDO ASSINATURA", value: "AGUARDANDO ASSINATURA" },
	{ id: 5, label: "AGUARDANDO FATURAMENTO", value: "AGUARDANDO FATURAMENTO" },
	{ id: 6, label: "AGUARDANDO PENDÊNCIAS", value: "AGUARDANDO PENDÊNCIAS" },
	{ id: 7, label: "AGUARDANDO RESPOSTA", value: "AGUARDANDO RESPOSTA" },
	{ id: 8, label: "APROVADO COM OBRAS", value: "APROVADO COM OBRAS" },
	{ id: 9, label: "APROVADO COM REDUÇÃO", value: "APROVADO COM REDUÇÃO" },
	{ id: 10, label: "APROVADO NOTURNO", value: "APROVADO NOTURNO" },
	{ id: 11, label: "APROVADO", value: "APROVADO" },
	{ id: 12, label: "REPROVADO", value: "REPROVADO" },
	{ id: 13, label: "SUSPENSO", value: "SUSPENSO" },
	{ id: 14, label: "REPROVADO COM REDUÇÃO", value: "REPROVADO COM REDUÇÃO" },
];
export const inverterFixationOptions = [
	{ id: 1, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
	{ id: 2, label: "ALVENARIA", value: "ALVENARIA" },
	{ id: 3, label: "LANCE DE MURO", value: "LANCE DE MURO" },
	{ id: 4, label: "PILAR", value: "PILAR" },
	{ id: 5, label: "OUTRO(DESCREVA EM OBSERVAÇÕES)", value: "OUTRO(DESCREVA EM OBSERVAÇÕES)" },
];

export const ElectricalInstallationGroups = [
	{ id: 1, label: "RESIDENCIAL", value: "RESIDENCIAL" },
	{ id: 2, label: "COMERCIAL", value: "COMERCIAL" },
	{ id: 3, label: "INDUSTRIAL", value: "INDUSTRIAL" },
	{ id: 4, label: "RURAL", value: "RURAL" },
];
export const roofTiles = [
	{ id: 1, label: "NÃO DEFINIDO", value: "NÃO DEFINIDO" },
	{ id: 2, label: "PORTUGUESA", value: "PORTUGUESA" },
	{ id: 3, label: "FRANCESA", value: "FRANCESA" },
	{ id: 4, label: "ROMANA", value: "ROMANA" },
	{ id: 5, label: "CIMENTO", value: "CIMENTO" },
	{ id: 6, label: "ETHERNIT", value: "ETHERNIT" },
	{ id: 7, label: "SANDUÍCHE", value: "SANDUÍCHE" },
	{ id: 8, label: "AMERICANA", value: "AMERICANA" },
	{ id: 9, label: "ZINCO", value: "ZINCO" },
	{ id: 10, label: "CAPE E BICA", value: "CAPE E BICA" },
	{ id: 11, label: "LAJE", value: "LAJE" },
];
export const structureTypes = [
	{ id: 1, label: "INCLINAÇÃO", value: "INCLINAÇÃO" },
	{ id: 2, label: "SOLO", value: "SOLO" },
	{ id: 3, label: "TELHADO", value: "TELHADO" },
	{ id: 4, label: "BARRACÃO", value: "BARRACÃO" },
	{ id: 5, label: "CARPORT", value: "CARPORT" },
	{ id: 6, label: "ESTRUTURA PERSONALIZADA", value: "ESTRUTURA PERSONALIZADA" },
	{ id: 7, label: "N/A", value: "N/A" },
];
export const crmStructureTypes = [
	{ id: 1, label: "Carport", value: "Carport" },
	{ id: 2, label: "Cerâmico", value: "Cerâmico" },
	{ id: 3, label: "Fibrocimento", value: "Fibrocimento" },
	{ id: 4, label: "Laje", value: "Laje" },
	{ id: 5, label: "Metálico", value: "Metálico" },
	{ id: 6, label: "Zipado", value: "Zipado" },
	{ id: 7, label: "Solo", value: "Solo" },
	{ id: 8, label: "Sem estrutura", value: "Sem estrutura" },
];
export const supplyOptions = {
	GRAMPO: {
		tipos: ["FINAL", "INTERMEDIÁRIO"],
		grandeza: "UNIDADE",
	},
	TRILHO: {
		tipos: ["1,85", "2,20", "2,36", "2,40", "2,50", "3,20", "3,30", "4,20", "4,70", "4,80"],
		grandeza: "UNIDADE",
	},
	"PARAFUSO FIBROCIMENTO": {
		tipos: ["MADEIRA", "FERRO"],
		grandeza: "UNIDADE",
	},
	"PAR DE JUNÇÃO": {
		tipos: ["TRILHO"],
		grandeza: "UNIDADE",
	},
	CABO: {
		tipos: ["SOLAR(VERMELHO)", "SOLAR(PRETO)"],
		grandeza: "METRO",
	},
	"CONECTOR MC4": {
		tipos: ["-"],
		grandeza: "UNIDADE",
	},
	"ESTRUTURA SOLO": {
		tipos: ["MESA DUPLA"],
		grandeza: "MESA",
	},
};
export const additionalServicesResponsibilityOptions = [
	{ id: 1, label: "NÃO", value: "NÃO" },
	{ id: 2, label: "SIM - RESPONSABILIDADE DO CLIENTE", value: "SIM - RESPONSABILIDADE DO CLIENTE" },
	{ id: 3, label: "SIM - RESPONSABILIDADE DA EMPRESA", value: "SIM - RESPONSABILIDADE DA EMPRESA" },
];
export const amperageOptions = [
	{ id: 1, label: "40A", value: "40A" },
	{ id: 2, label: "50A", value: "50A" },
	{ id: 3, label: "60A", value: "60A" },
	{ id: 4, label: "63A", value: "63A" },
	{ id: 5, label: "70A", value: "70A" },
	{ id: 6, label: "90A", value: "90A" },
	{ id: 7, label: "100A", value: "100A" },
	{ id: 8, label: "200A", value: "200A" },
];
export const paymentMethods = [
	{ id: 1, label: "À VISTA (GERAL)", value: "À VISTA (GERAL)", apportionment: false, modality: null },
	{ id: 2, label: "À VISTA (DINHEIRO)", value: "À VISTA (DINHEIRO)", apportionment: false, modality: null },
	{ id: 3, label: "À VISTA (PIX)", value: "À VISTA (PIX)", apportionment: false, modality: null },
	{ id: 4, label: "À VISTA (DÉBITO)", value: "À VISTA (DÉBITO)", apportionment: false, modality: null },
	{ id: 5, label: "BOLETO", value: "BOLETO", apportionment: true, modality: "SIMPLES" },
	{ id: 6, label: "PARCELADO (CRÉDITO)", value: "PARCELADO (CRÉDITO)", apportionment: true, modality: "SIMPLES" },
	{ id: 7, label: "FINANCIAMENTO", value: "FINANCIAMENTO", apportionment: true, modality: "COMPOSTOS" },
];
export const energyPATypes = [
	{ id: 1, label: "CONTRA À REDE", value: "CONTRA À REDE" },
	{ id: 2, label: "À FAVOR DA REDE", value: "À FAVOR DA REDE" },
];
export const energyPAConnectionTypes = [
	{ id: 1, label: "AÉREO", value: "AÉREO" },
	{ id: 2, label: "SUBTERRÂNEO", value: "SUBTERRÂNEO" },
];
export const energyMeterBoxModels = [
	{ id: 1, label: "CM-1", value: "CM-1" },
	{ id: 2, label: "CM-2", value: "CM-2" },
	{ id: 3, label: "CM-3", value: "CM-3" },
	{ id: 4, label: "CM-4", value: "CM-4" },
	{ id: 5, label: "CM-8", value: "CM-8" },
	{ id: 6, label: "CM-9", value: "CM-9" },
	{ id: 7, label: "CM-13", value: "CM-13" },
	{ id: 8, label: "CM-14", value: "CM-14" },
	{ id: 9, label: "CM-18", value: "CM-18" },
];
export const technicalAnalysisReportTypes = [
	{
		id: 1,
		label: "LAUDO TÉCNICO(URBANO)",
		value: "LAUDO TÉCNICO(URBANO)",
	},
	{
		id: 2,
		label: "LAUDO SIMPLES(URBANO)",
		value: "LAUDO SIMPLES(URBANO)",
	},
	{
		id: 3,
		label: "LAUDO INTERMEDIÁRIO(URBANO)",
		value: "LAUDO INTERMEDIÁRIO(URBANO)",
	},
	{
		id: 4,
		label: "LAUDO TÉCNICO(RURAL)",
		value: "LAUDO TÉCNICO(RURAL)",
	},
	{
		id: 5,
		label: "LAUDO SIMPLES(RURAL)",
		value: "LAUDO SIMPLES(RURAL)",
	},
	{
		id: 6,
		label: "FORMULÁRIO(URBANO)",
		value: "FORMULÁRIO(URBANO)",
	},
	{
		id: 7,
		label: "FORMULÁRIO(RURAL)",
		value: "FORMULÁRIO(RURAL)",
	},
];
export const orientationIcons = {
	LESTE: MdEast,
	NORDESTE: MdNorthEast,
	NORTE: MdNorth,
	NOROESTE: MdNorthWest,
	OESTE: MdWest,
	SUDOESTE: MdSouthWest,
	SUL: MdSouth,
	SUDESTE: MdSouthEast,
};

export const revenueSources = [
	{
		id: 1,
		label: "SISTEMA FOTOVOLTAICO",
		value: "SISTEMA FOTOVOLTAICO",
	},
	{
		id: 2,
		label: "SISTEMA FOTOVOLTAICO (OFF GRID)",
		value: "SISTEMA FOTOVOLTAICO (OFF GRID)",
	},
	{
		id: 3,
		label: "AUMENTO DE SISTEMA FOTOVOLTAICO",
		value: "AUMENTO DE SISTEMA FOTOVOLTAICO",
	},
	{
		id: 4,
		label: "BOMBA SOLAR",
		value: "BOMBA SOLAR",
	},
	{
		id: 5,
		label: "OPERAÇÃO E MANUTENÇÃO",
		value: "OPERAÇÃO E MANUTENÇÃO",
	},
	{
		id: 6,
		label: "TROCA DE PADRÃO",
		value: "TROCA DE PADRÃO",
	},
	{
		id: 7,
		label: "REFORMA DE PADRÃO",
		value: "REFORMA DE PADRÃO",
	},
	{
		id: 8,
		label: "MANUTENÇÃO CORRETIVA",
		value: "MANUTENÇÃO CORRETIVA",
	},
	{
		id: 9,
		label: "MANUTENÇÃO PREVENTIVA",
		value: "MANUTENÇÃO PREVENTIVA",
	},
	{
		id: 10,
		label: "MONTAGEM E DESMONTAGEM",
		value: "MONTAGEM E DESMONTAGEM",
	},
	{
		id: 11,
		label: "TROCA DE STRING BOX",
		value: "TROCA DE STRING BOX",
	},
	{
		id: 12,
		label: "SUBESTAÇÃO DE ENERGIA",
		value: "SUBESTAÇÃO DE ENERGIA",
	},
	{
		id: 13,
		label: "HOMOLOGAÇÃO",
		value: "HOMOLOGAÇÃO",
	},
	{
		id: 14,
		label: "SEGURO DE SISTEMA FOTOVOLTAICO",
		value: "SEGURO DE SISTEMA FOTOVOLTAICO",
	},
	{
		id: 15,
		label: "PRODUTOS",
		value: "PRODUTOS",
	},
	{
		id: 16,
		label: "CONSÓRCIO DE ENERGIA",
		value: "CONSÓRCIO DE ENERGIA",
	},
	{
		id: 18,
		label: "MONITORAMENTO",
		value: "MONITORAMENTO",
	},
	{ id: 19, label: "OUTRAS RECEITAS", value: "OUTRAS RECEITAS" },
];

export const PurchaseControlStatus = [
	{ id: 1, label: "PENDENTE", value: "PENDENTE", deadlineDays: null },
	{ id: 2, label: "EM COTAÇÃO", value: "EM COTAÇÃO", deadlineDays: 2 },
	{ id: 3, label: "AGUARDANDO APROVAÇÃO", value: "AGUARDANDO APROVAÇÃO", deadlineDays: null },
	{ id: 7, label: "AGUARDANDO COMPRA", value: "AGUARDANDO COMPRA", deadlineDays: 2 },
	{ id: 4, label: "AGUARDANDO NOTA FUTURA", value: "AGUARDANDO NOTA FUTURA", deadlineDays: 2 },
	{ id: 5, label: "AGUARDANDO PAGAMENTO", value: "AGUARDANDO PAGAMENTO", deadlineDays: 3 },
	{ id: 6, label: "AGUARDANDO NOTA FINAL", value: "AGUARDANDO NOTA FINAL", deadlineDays: 7 },
	{ id: 8, label: "AGUARDANDO SEPARAÇÃO", value: "AGUARDANDO SEPARAÇÃO", deadlineDays: 7 },
	{ id: 11, label: "AGUARDANDO DESPACHE", value: "AGUARDANDO DESPACHE", deadlineDays: 7 },
	{ id: 12, label: "AGUARDANDO ENTREGA", value: "AGUARDANDO ENTREGA", deadlineDays: 7 },
	{ id: 13, label: "PENDÊNCIAS", value: "PENDÊNCIAS", deadlineDays: null },
	{ id: 14, label: "CONCLUÍDA", value: "CONCLUÍDA", deadlineDays: null },
];
export const PurchaseCompositionItemCategories = [
	{ id: 1, label: "MÓDULO", value: "MÓDULO", icon: FaSolarPanel as React.ComponentType },
	{ id: 2, label: "INVERSOR", value: "INVERSOR", icon: TbTopologyFull as React.ComponentType },
	{ id: 3, label: "INSUMO", value: "INSUMO", icon: MdOutlineSettingsInputComponent as React.ComponentType },
	{ id: 4, label: "ESTRUTURA", value: "ESTRUTURA", icon: BsFillHouseFill as React.ComponentType },
	{ id: 5, label: "PADRÃO", value: "PADRÃO", icon: MdElectricMeter as React.ComponentType },
	{ id: 6, label: "OUTROS", value: "OUTROS", icon: BsCart as React.ComponentType },
];
export const PurchaseDeliveryStatus: { id: number; label: string; value: TPurchaseControl["entrega"]["status"] }[] = [
	{ id: 1, label: "AGUARDANDO COMPRA", value: "AGUARDANDO COMPRA" },
	{ id: 2, label: "AGUARDANDO DESPACHE", value: "AGUARDANDO DESPACHE" },
	{ id: 3, label: "EM ROTA", value: "EM ROTA" },
	{ id: 4, label: "ENTREGUE", value: "ENTREGUE" },
];

export const TagsColorPalette = [
	{ primaria: "#FF0000", secundaria: "#FFCCCB" },
	{ primaria: "#0000FF", secundaria: "#E6E6FF" },
	{ primaria: "#008000", secundaria: "#C1E1C1" },
	{ primaria: "#FEAD41", secundaria: "#FFFACD" },
	{ primaria: "#800080", secundaria: "#E6E6FA" },
	{ primaria: "#C13F55", secundaria: "#FFE4E1" },
	{ primaria: "#4B0082", secundaria: "#E6E6FA" },
	{ primaria: "#000000", secundaria: "#F8F8F8" },
	{ primaria: "#FF9D00", secundaria: "#FFF4E2" },
	{ primaria: "#07ABAB", secundaria: "#E0FFFF" },
	{ primaria: "#8B4513", secundaria: "#DFD0BC" },
	{ primaria: "#008CFF", secundaria: "#B0E0E6" },
	{ primaria: "#2E8B57", secundaria: "#98FB98" },
	{ primaria: "#DC143C", secundaria: "#FFCBB7" },
	{ primaria: "#9932CC", secundaria: "#E6E6FA" },
	{ primaria: "#FF1493", secundaria: "#FCD8DD" },
	{ primaria: "#003365", secundaria: "#87CEFA" },
	{ primaria: "#FF4500", secundaria: "#FCE0D4" },
	{ primaria: "#058A05", secundaria: "#B7FDB7" },
	{ primaria: "#ECAA02", secundaria: "#F3F0D3" },
];

export const FileReferenceCategories = [
	{ id: 1, label: "DOCUMENTOS", value: "DOCUMENTOS", restrict: false },
	{ id: 2, label: "ANÁLISES TÉCNICAS", value: "ANÁLISES TÉCNICAS", restrict: false },
	{ id: 3, label: "CONTRATOS", value: "CONTRATOS", restrict: false },
	{ id: 4, label: "HOMOLOGAÇÕES", value: "HOMOLOGAÇÕES", restrict: false },
	{ id: 5, label: "PROJETOS", value: "PROJETOS", restrict: false },
	{ id: 6, label: "COMPRAS", value: "COMPRAS", restrict: false },
	{ id: 7, label: "FINANCEIRO", value: "FINANCEIRO", restrict: true },
	{ id: 8, label: "SERVIÇOS", value: "SERVIÇOS", restrict: false },
	{ id: 9, label: "MANUTENÇÕES", value: "MANUTENÇÕES", restrict: false },
	{ id: 10, label: "OUTROS", value: "OUTROS", restrict: false },
];

export const ServiceOrderStatus = [
	{ id: 1, label: "PENDENTE", value: "PENDENTE" }, // add aguardando liberação
	{ id: 2, label: "AGUARDANDO PLANEJAMENTO", value: "AGUARDANDO PLANEJAMENTO" },
	{ id: 3, label: "AGUARDANDO LIBERAÇÃO", value: "AGUARDANDO LIBERAÇÃO" },
	{ id: 4, label: "AGUARDANDO AGENDAMENTO", value: "AGUARDANDO AGENDAMENTO" },
	{ id: 5, label: "AGUARDANDO EXECUÇÃO", value: "AGUARDANDO EXECUÇÃO" },
	{ id: 6, label: "EM EXECUÇÃO", value: "EM EXECUÇÃO" },
	{ id: 7, label: "CONCLUÍDA PARCIAL", value: "CONCLUÍDA PARCIAL" },
	{ id: 8, label: "CONCLUÍDA", value: "CONCLUÍDA" },
	{ id: 9, label: "CANCELADA", value: "CANCELADA" },
	{ id: 10, label: "PENDÊNCIAS", value: "PENDÊNCIAS" },
];
